---
  observer:
    entryes:
      logfile:
      - name: emerge_download_start
        path: /var/log/emerge-fetch.log
        store_position: no
        match:
          positive: ">>> Downloading '(?P<url>.+?)'"
      - name: emerge_download_done
        path: /var/log/emerge-fetch.log
        store_position: no
        match:
          positive: '.+? .+? \\((?P<avg_speed>.+?)\\) - ‘(?P<file_location>.+?)’ saved \\[(?P<file_size>.+?)/'
      - name: emerge_rsync_start
        path: /var/log/emerge.log
        store_position: no
        match:
          positive: ".+?: >>> Starting rsync with (?P<rsync_url>.+?)"
      - name: emerge_start
        path: /var/log/emerge.log
        store_position: no
        match:
          positive: '.+?:  >>> emerge \\((?P<package_num>.+?) of (?P<queue_size>.+?)\\) (?P<package>.+?) to (?P<destination>.*)'
      - name: emerge_done
        path: /var/log/emerge.log
        store_position: no
        match:
          positive: '.+?:  ::: completed emerge \\((?P<package_num>.+?) of (?P<queue_size>.+?)\\) (?P<package>.+?) to (?P<destination>.*)'
