---
  ansible_connection: network_cli
  ansible_network_os: routeros
  ansible_user: "{{ mikrotik_secrets.superuser.login }}"
  ansible_password: "{{ mikrotik_secrets.superuser.password }}"

  firewall:
    host_to_internet:
      ddns:
        name: "DDNS"
        ports:
        - 15252
