---
  firewall:
    trusted_to_internet:
      services:
      - discord
      - email
      - fantasyradio
      - ftp
      - google
      - irc
      - rtsp_streams
      - socks5
      - steam
      - telegram
      - torrent
      - ultima_online
      - whatsapp
      - tracepath
