---
  - name: Configuring systemd journald
    template:
      src: etc/systemd/journald.conf.j2
      dest: /etc/systemd/journald.conf
      owner: root
      group: root
      mode: 0644
    notify:
    - restart journald

  - name: Создание каталогов для journald
    file:
      dest: "{{ item }}"
      state: directory
      owner: root
      group: systemd-journal
      mode: 02755
    with_items:
      - /var/log/journal

  - name: Enabling journald service
    service:
      name: "{{ item }}"
      enabled: yes
    loop:
      - systemd-journald
