---
  - name: Configuring journald
    template:
      src: etc/systemd/journald.conf.j2
      dest: /etc/systemd/journald.conf
      owner: root
      group: root
      mode: 0644
    notify:
    - restart journald
