---
  - name: Устанавливаем необходимые пакеты
    include_role:
      name: portage
      tasks_from: install_package
    vars:
      package: { name: www-servers/nginx }
    tags:
    - packages

  - name: create dirs for nginx
    file:
      dest: "{{ item }}"
      state: directory
      owner: nginx
    with_items:
      - /etc/nginx/sites
      - /var/log/nginx
      - /var/www
      - /var/www/files

  - name: deploy nginx configuration
    template:
      owner: nginx
      group: nginx
      src: etc/nginx/nginx.conf.j2
      dest: /etc/nginx/nginx.conf
      mode: 0644
    notify:
    - reload nginx

  - name: deploy simple fileshare
    template:
      owner: nginx
      group: nginx
      src: etc/nginx/sites/simple_filesharing.conf.j2
      dest: /etc/nginx/sites/simple_filesharing.conf
      mode: 0644
    notify:
    - reload nginx

  - name: Настройка ротации логов nginx
    import_role:
      name: logrotate
      tasks_from: rotate
    vars:
      lr:
        name: nginx
        files:
        - /var/log/nginx/error.log
        - /var/log/nginx/error_log
        options:
        - missingok
        - rotate 4
        - daily
        - compress
        postrotate: "test -r /run/nginx.pid && kill -USR1 `cat /run/nginx.pid`"

  - name: Прикручиваем мониторинг
    include_role:
      name: telegraf
      tasks_from: deploy_nginx_status_plugin
    # notify:
    # - reload nginx

  - name: Install nginx service
    import_role:
      name: systemd_unit
      tasks_from: setup_service
    vars:
      service:
        name: nginx-daemon
        description: The nginx HTTP and reverse proxy server
        type: forking
        pid_file: "{{ nginx.pid_file }}"
        exec_start_pre: /usr/sbin/nginx -t
        exec_start: /usr/sbin/nginx
        exec_stop: /bin/kill -QUIT $MAINPID
        exec_reload: /bin/kill -HUP $MAINPID
        after:
        - network-online.target
        wanted_by:
        - multi-user.target
        on_changed: reloaded
        state: started
        enabled: yes
        replaces:
        - nginx
