---
  - name: Устанавливаем необходимые пакеты
    include_role:
      name: portage
      tasks_from: install_package
    vars:
      package: { name: www-servers/nginx }
    tags:
    - packages

  - name: create dirs for nginx
    file:
      dest: "{{ item }}"
      state: directory
      owner: nginx
    with_items:
      - /etc/nginx/sites
      - /var/log/nginx
      - /var/www
      - /var/www/files

  - name: deploy nginx configuration
    template:
      owner: nginx
      group: nginx
      src: etc/nginx/nginx.conf.j2
      dest: /etc/nginx/nginx.conf
      mode: 0644
    notify:
    - reload nginx

  - name: deploy simple fileshare
    template:
      owner: nginx
      group: nginx
      src: etc/nginx/sites/simple_filesharing.conf.j2
      dest: /etc/nginx/sites/simple_filesharing.conf
      mode: 0644
    notify:
    - reload nginx

  - name: Install nginx daemon service
    template:
      src: etc/systemd/system/nginx-daemon.service.j2
      dest: /etc/systemd/system/nginx-daemon.service
      owner: root
      group: root
      mode: 0644
    notify:
    - systemd daemon reload
    - restart nginx

  - name: Прикручиваем мониторинг
    include_role:
      name: telegraf
      tasks_from: deploy_nginx_status_plugin
    notify:
    - reload nginx

  - name: Stopping and disabling system nginx service
    service:
      name: nginx
      enabled: no
      state: stopped

  - name: Enabling services
    service:
      name: nginx-daemon
      enabled: yes
