---
  - name: Устанавливаем необходимые пакеты
    include_tasks: "{{ ansible_distribution }}/packages.yaml"
    tags:
    - packages

  - name: create dirs for nginx
    file:
      dest: "{{ item }}"
      state: directory
      owner: "{{ dist_difference.nginx.user[ansible_distribution] }}"
    with_items:
      - /etc/nginx/sites
      - /var/log/nginx
      - /var/www
      - /var/www/files
      - /run/nginx

  - name: deploy nginx configuration
    template:
      owner: "{{ dist_difference.nginx.user[ansible_distribution] }}"
      group: "{{ dist_difference.nginx.user[ansible_distribution] }}"
      src: etc/nginx/nginx.conf.j2
      dest: /etc/nginx/nginx.conf
      mode: 0644
    notify:
    - reload nginx

  - name: deploy simple fileshare
    template:
      owner: nginx
      group: nginx
      src: etc/nginx/sites/simple_filesharing.conf.j2
      dest: /etc/nginx/sites/simple_filesharing.conf
      mode: 0644
    notify:
    - reload nginx
    vars:
      target:
        name: files

  # - name: Deploy nginx site
  #   import_role:
  #     name: nginx
  #     tasks_from: simple_site
  #   vars:
  #     target:
  #       name: test

  - name: Настройка ротации логов nginx
    import_role:
      name: logrotate
      tasks_from: rotate
    vars:
      lr:
        name: nginx
        files:
        - /var/log/nginx/error.log
        - /var/log/nginx/error_log
        options:
        - missingok
        - rotate 4
        - daily
        - compress
        postrotate: "test -r {{ merged_vars.nginx.pid_file }} && kill -USR1 `cat {{ merged_vars.nginx.pid_file }}`"

  - name: Прикручиваем мониторинг
    include_role:
      name: telegraf
      tasks_from: deploy_nginx_status_plugin
    # notify:
    # - reload nginx

  - name: Install nginx service
    import_role:
      name: systemd_unit
      tasks_from: setup_service
    vars:
      service:
        name: nginx-daemon
        description: The nginx HTTP and reverse proxy server
        type: forking
        pid_file: "{{ merged_vars.nginx.pid_file }}"
        exec_start_pre: /usr/sbin/nginx -t
        exec_start: /usr/sbin/nginx
        exec_stop: /bin/kill -QUIT $MAINPID
        exec_reload: /bin/kill -HUP $MAINPID
        directoryes:
        - /run/nginx
        after:
        - network-online.target
        wanted_by:
        - multi-user.target
        on_changed: reloaded
        state: started
        enabled: yes
        replaces:
        - nginx
