---
  # - debug:
  #     msg: "{{ hostvars[target.hoster].ansible_facts.distribution }}"

  - name: "{{ target.name }} : Deploying nginx configuration"
    template:
      owner: "{{ dist_difference.nginx.user[dist] }}"
      group: "{{ dist_difference.nginx.user[dist] }}"
      src: etc/nginx/sites/simple_proxy.conf.j2
      dest: "/etc/nginx/sites/{{ target.name }}.conf"
      mode: 0644
    vars:
      hosted_at: "{{ target.hoster | default(inventory_hostname) }}"
      dist: "{{ hostvars[target.hoster | default(inventory_hostname)].ansible_facts.distribution | default(ansible_distribution) }}"
    notify:
    - reload nginx

  - name: "{{ target.name }} : Настройка ротации"
    import_role:
      name: logrotate
      tasks_from: rotate
    vars:
      lr:
        name: "nginx-{{ target.name }}"
        files:
        - "/var/log/nginx/{{ target.name }}.access.log"
        - "/var/log/nginx/{{ target.name }}.error.log"
        - "/var/log/nginx/{{ target.name }}.internet.access.log"
        - "/var/log/nginx/{{ target.name }}.internet.error.log"
        options:
        - missingok
        - rotate 7
        - daily
        - delaycompress
        - sharedscripts
        postrotate: "test -r {{ nginx.pid_file }} && kill -USR1 `cat {{ nginx.pid_file }}`"
