---
  - name: Деплоим статус для nginx
    template:
      owner: nginx
      group: nginx
      src: etc/nginx/sites/status.conf.j2
      dest: /etc/nginx/sites/status.conf
      mode: 0644
    notify:
    - reload nginx

  - name: Настройка ротации логов статуса
    import_role:
      name: logrotate
      tasks_from: rotate
    vars:
      lr:
        name: nginx-status
        files:
        - /var/log/nginx/stub_status.error.log
        options:
        - missingok
        - rotate 7
        - daily
        - delaycompress
        - sharedscripts
        postrotate: "test -r /run/nginx.pid && kill -USR1 `cat /run/nginx.pid`"
