---
  - name: "{{ service.name }} : Устанавливаем юнит сервиса"
    template:
      src: "etc/systemd/system/template.service.j2"
      dest: "/etc/systemd/system/{{ service.name }}.service"
      owner: root
      group: root
      mode: 0644
    register: service_template_result

  - name: "{{ service.name }} : Перезагрузка сервиса"
    systemd:
      daemon_reload: yes
      name: "{{ service.name }}"
      state: "{{ service.on_changed | default('restarted') }}"
    when: service_template_result.changed

  - name: "{{ service.name }} : Управление запуском"
    systemd:
      name: "{{ service.name }}"
      enabled: "{{ service.enabled | default(False) }}"
      state: "{{ service.state | default('stopped') }}"
