---
  - name: Устанавливаем юнит таймера
    template:
      src: "etc/systemd/system/template.timer.j2"
      dest: "/etc/systemd/system/{{ timer.name }}.timer"
      owner: root
      group: root
      mode: 0644
    register: ts
    notify:
    - systemd daemon reload

  - name: Устанавливаем сервис для таймера
    import_role:
      name: systemd_unit
      tasks_from: setup_service
    vars:
      service:
        name: "{{ timer.name }}"
        description: "Timer '{{ timer.name }}' service: {{ timer.description }}"
        command: "{{ timer.command }}"
        user: "{{ timer.user }}"
        pid_file: "/run/timer-service-{{ timer.name }}.pid"

  - name: Включаем таймер
    service:
      name: "{{ timer.name }}.timer"
      state: restarted
      daemon_reload: yes
      enabled: yes
    when: ts.changed
