---
  - name: "{{ service.name }} : Устанавливаем окружение сервиса"
    template:
      src: "etc/default/environments.j2"
      dest: "/etc/default/{{ service.name }}.env"
      owner: root
      group: root
      mode: 0644
    when: service.environments is defined

  - name: "{{ service.name }} : Устанавливаем юнит сервиса"
    template:
      src: "etc/systemd/system/template.service.j2"
      dest: "/etc/systemd/system/{{ service.name }}.service"
      owner: root
      group: root
      mode: 0644
    register: service_template_result

  - name: "{{ service.name }} : Перезагрузка сервиса"
    systemd:
      daemon_reload: yes
      name: "{{ service.name }}"
      state: "{{ service.on_changed | default('restarted') }}"
    when: service_template_result.changed and
          (service.standalone | default(True))

  - name: "{{ service.name }} : Управление запуском"
    systemd:
      name: "{{ service.name }}"
      enabled: "{{ service.enabled | default(False) }}"
      state: "{{ service.state | default('stopped') }}"
    when: (service.standalone | default(True))

  - name: "{{ service.name }} : Запрет замещаемых сервисов"
    systemd:
      name: "{{ item }}"
      enabled: no
      masked: yes
      state: stopped
    loop: "{{ service.replaces }}"
    when: service.replaces is defined and
          (service.standalone | default(True))
