---
  - name: Добавляем пользователя
    import_role:
      name: system_user
      tasks_from: setup_user
    vars:
      user:
        name: "{{ merged_vars.factorio.user.name }}"
        password: "{{ merged_vars.factorio.user.pw  }}"
        comment: Factorio runner
        groups:
        - users

  - name: Создаём каталоги
    file:
      dest: "{{ item }}"
      state: directory
      owner: "{{ merged_vars.factorio.user.name }}"
      group: "{{ merged_vars.factorio.user.name }}"
      mode: 0755
    loop:
      - "{{ merged_vars.factorio.paths.home }}"
      - "{{ merged_vars.factorio.paths.home }}/mods"
      - "{{ merged_vars.factorio.paths.home }}/saves"

  - name: Скачиваем и распаковываем factorio
    unarchive:
      src: "https://www.factorio.com/get-download/{{ merged_vars.factorio.version }}/headless/linux64"
      dest: "{{ merged_vars.factorio.paths.home }}/../"
      owner: "{{ merged_vars.factorio.user.name }}"
      group: "{{ merged_vars.factorio.user.name }}"
      validate_certs: no
      remote_src: yes
    notify:
    - restart factorio
    tags:
    - packages

  - name: Генерируем конфиги
    template:
      src: "{{ item }}.j2"
      dest: "/{{ item }}"
      owner: "{{ merged_vars.factorio.user.name }}"
      group: "{{ merged_vars.factorio.user.name }}"
      mode: 0644
    loop:
    - opt/factorio/server-settings.json
    - opt/factorio/server-adminlist.json
    notify:
    - restart factorio

  - name: Установка стартового скрипта
    template:
      src: opt/factorio/start.sh.j2
      dest: /opt/factorio/start.sh
      owner: "{{ merged_vars.factorio.user.name }}"
      group: "{{ merged_vars.factorio.user.name }}"
      mode: 0755
    notify:
    - restart factorio

  - name: Устанавливаем моды
    include_role:
      name: factorio
      tasks_from: mod_install
    vars:
      mod: "{{ item }}"
    loop: "{{ merged_vars.factorio.mods }}"
    tags:
    - mods

  - name: Генерируем список модов
    template:
      src: opt/factorio/mods/mod-list.json.j2
      dest: /opt/factorio/mods/mod-list.json
      owner: "{{ merged_vars.factorio.user.name }}"
      group: users
      mode: 0644
    notify:
    - restart factorio

  - name: Устанавливаем сервис
    import_role:
      name: systemd_unit
      tasks_from: setup_service
    vars:
      service:
        name: factorio
        description: Factorio server daemon
        restart_sec: 16s
        working_dir: "{{ merged_vars.factorio.paths.home }}"
        exec_start: "{{ merged_vars.factorio.paths.home }}/start.sh"
        user: "{{ merged_vars.factorio.user.name }}"
        group: "{{ merged_vars.factorio.user.name }}"
        after:
        - network-online.target
        wanted_by:
        - multi-user.target
        on_changed: "{{ 'restarted' if merged_vars.factorio.active else 'noop' }}"
        state: "{{ 'started' if merged_vars.factorio.active else 'stopped' }}"
        enabled: "{{ merged_vars.factorio.active }}"
