---
  network:
  - name: "Internal"
    ifname: "internal_0"
    dns:
      aliases:
        - grafana
        - prometheus
        - ntp
    mac: "94:de:80:6c:66:b0"
    ip: "{{ query('ship', 'ip', 1) | first }}"
    network: 'home'
    type: 'static'

  - name: "External KIS"
    ifname: "external_kis_0"
    tunnel: "external_he_0"
    dns:
      aliases:
        - www
        - cameras
        - test
        - minecraft
    mac: "50:3e:aa:04:8f:b0"
    ip:
      ipv4: "{{ query('ship', 'kis_ip', 2) | first }}"
    network: 'kis'
    type: 'static'
    route_table: 100

  - name: "External RT"
    ifname: "external_rt_0"
    type: "pppoe"
    bridge: "bridge_rt_0"
    ip:
      ipv4: "{{ query('ship', 'rt_ip', 3) | first }}"
    route_table: 101

  - name: "Bridge RT"
    ifname: "bridge_rt_0"
    mac: "50:3e:aa:04:cb:21"
    type: "bridge"
    ip:
      ipv4: 'dynamic'

  - name: "External HeNet"
    dns:
      aliases:
        - www
        - cameras
        - test
        - minecraft
    ifname: "external_he_0"
    need_netdev: yes
    ip:
      ipv6: "{{ query('ship', 'henet_ip', 2) | first }}"
    network: 'henet'
    type: 'static'

  # - name: "Tunnel Tor"
  #   ifname: "tunnel_tor_0"
  #   type: "virtual"
  #   network: 'tor'
  #   mac: "50:3e:aa:04:cb:20"
  #   ip: # "{{ query('ship', 'ip', 8) | first }}"
  #     ipv4: "{{ query('ship', 'tor_ip', 'ipv4', 1) | first }}"
  #     ipv6: "{{ query('ship', 'tor_ip', 'ipv6', 1) | first }}"
