---
  observer:
    entryes:
      grafana:
        listen:
          port: 3214
          interface: '::1'
      journald:
      - name: dhcpd4_dhcpack_to
        match:
          positive: 'dhcpd.*: DHCPACK to (?P<address>.+?) \\((?P<mac>.+?)\\) via (?P<interface>.*)'
      - name: dhcpd4_dhcpack_to_guest
        match:
          positive: 'dhcpd.*: DHCPACK on (?P<address>.+?) to (?P<mac>.+?) \\((?P<hostname>.+?)\\) via (?P<interface>.*)'
      - name: dhcpd6_na_to
        match:
          positive: 'dhcpd.*: Reply NA: address (?P<address>.+?) to client with duid (?P<duid>.+?) iaid = (?P<iaid>.+?) static'
      - name: dhcpd6_na_to_guest
        match:
          positive: 'dhcpd.*: Reply NA: address (?P<address>.+?) to client with duid (?P<duid>.+?) iaid = (?P<iaid>.+?) valid for (?P<valid_period_seconds>.+?) seconds'
