---
  - name: Устанавливаем необходимые пакеты
    include_role:
      name: portage
      tasks_from: install_package
    vars:
      package: "{{ item }}"
    loop:
    - { name: app-antivirus/clamav, use: { enabled: [clamdtop, bzip2, iconv, ipv6, xml], disabled: [metadata-analysis-api, milter, test, clamsubmit, libclamav-only] } }
    tags:
    - packages
