---
  video_nvidia_smi_location: /opt/bin/nvidia-smi
  telegraf:
    listen:
      port: 9101
    plugins:
      ping:
        count: 8
        interval: 0.2
        timeout: '{{ monitoring.collect.interval / 2 }}'
        deadline: '{{ monitoring.collect.interval }}'
