---
- hosts: gate
  remote_user: root
  vars_files:
  - vars/network.yaml
  # - vars/iptables-default.yaml

  handlers:
  - import_tasks: handlers/systemd-base.yaml
  - import_tasks: handlers/iptables.yaml

  tasks:

  # - name: Reset rules
  #   iptables:
  #     flush: True

  - name: "Set the policy for {{ item.0 }}"
    iptables:
      chain: "{{ item.1.chain }}"
      policy: "{{ item.1.policy }}"
      ip_version: "{{ item.0 }}"
    notify:
    - "restart iptables.{{ item.0 }}"
    - finish iptables rules
    with_nested:
    - [ 'ipv6', 'ipv4' ]
    - [{ chain: INPUT,   policy: ACCEPT }, { chain: OUTPUT,  policy: ACCEPT }, { chain: FORWARD, policy: ACCEPT }]

  - name: Create Iptables NAT
    include_tasks: tasks/iptables/main-nat.yaml
    # loop: "{{ network|selectattr('ifname', 'match', 'external_.*')|list }}"
    # loop_control:
    #   loop_var: ext_interface

  - name: Iptables allow ICMP
    iptables:
      chain: "{{ item.1 }}"
      jump: ACCEPT
      ip_version: "{{ item.0 }}"
      protocol: icmp
      comment: "Allow ICMP for {{ item.0 }}"
      # state: absent
    notify:
    - "restart iptables.{{ item.0 }}"
    - finish iptables rules
    with_nested:
    - [ 'ipv6', 'ipv4' ]
    - [ 'INPUT', 'OUTPUT' ]

  - name: Iptables ESTABLISHED, RELATED
    iptables:
      chain: INPUT
      ctstate: ESTABLISHED,RELATED
      jump: ACCEPT
      ip_version: "{{ item }}"
      comment: "Allow established and related for {{ item }}"
    notify:
    - "restart iptables.{{ item }}"
    - finish iptables rules
    with_items:
    - ipv4
    - ipv6

  - name: "Apply per-host rules"
    include_tasks: tasks/iptables/host-rules.yaml
    loop: "{{ query('inventory_hostnames', 'all')|difference(['gate']) }}"
    loop_control:
      loop_var: target_hostname

  - name: "Apply per-group rules"
    include_tasks: tasks/iptables/group-rules.yaml
    loop: "{{ groups|difference(['all','ungrouped','gateways']) }}"
    loop_control:
      loop_var: target_groupname

  - name: "Apply global rules"
    include_tasks: tasks/iptables/global-rules.yaml

  - name: "Apply to gate rules"
    include_tasks: tasks/iptables/to-host-rules.yaml
