---
- hosts: workstations-linux,gate
  remote_user: root

  tasks:
  - name: "Check interface name size"
    fail:
      msg: "Name of interface {{ item.ifname }} ({{ item.name }}) longer than 15 symbols"
    when: item.ifname is defined and
          item.ifname | length > 15
    loop: "{{ network }}"
