---
- hosts: workstations-linux,gate
  remote_user: root
  vars_files:
  - vars/network.yaml
  - vars/node_exporter.yaml

  handlers:
  - import_tasks: handlers/systemd.yaml

  tasks:

  - name: Install packages
    portage:
      package: "{{ item }}"
      state: present
    with_items:
    - app-metrics/node_exporter

  - name: create dirs for node_exporter
    file:
      dest: "{{ item }}"
      state: directory
      owner: node_exporter
    with_items:
      - /var/lib/node_exporter/textfile_collector

  - name: deploy node_exporter configuration
    template:
      owner: node_exporter
      src: templates/gate/etc/systemd/system/node_exporter.service.j2
      dest: /etc/systemd/system/node_exporter.service
      mode: 644
    notify:
    - systemd daemon reload
    - restart node_exporter

  - name: Deploy config to prometheus
    template:
      src: templates/gate/etc/prometheus/file_sd_configs/node_exporter.yaml.j2
      dest: "/etc/prometheus/file_sd_configs/{{ inventory_hostname }}.yaml"
      mode: 0644
      owner: prometheus
    delegate_to: gate
    notify:
    - restart gate prometheus

  - name: Enabling services
    service:
      name: "{{ item }}"
      enabled: yes
    loop:
      - node_exporter
