---
- hosts: workstations_windows
  vars_files:
  - vars/vault.yaml
  - vars/dns.yaml
  - vars/network.yaml
  roles:
  - { role: wmi_exporter, tags: [ wmi_exporter, monitoring ] }
  - { role: ntp, tags: ntp }
  - { role: windows_tune, tags: windows_tune }
  - { role: windows_oem, tags: windows_oem }
  - { role: packages, tags: packages }

# https://github.com/crombeen/ansible
