---
- hosts: gate
  remote_user: root
  vars_files:
  - vars/network.yaml
  - vars/firewall.yaml

  handlers:
  - import_tasks: handlers/systemd.yaml

  tasks:
  - name: Install packages
    portage:
      package: "{{ item }}"
      state: present
    with_items:
    - sys-apps/iproute2
    - net-firewall/nftables

  - name: Create conf directory
    file:
      path: /etc/nftables
      state: directory
      owner: root
      group: root
      mode: 0644

  - name: Install manager script
    template:
      src: templates/default/usr/local/bin/firewall-manager.sh.j2
      dest: /usr/local/bin/firewall-manager.sh
      owner: root
      group: root
      mode: 0744
    notify:
      - update firewall

  - name: Install firewall service
    template:
      src: templates/default/etc/systemd/system/firewall.service.j2
      dest: /etc/systemd/system/firewall.service
      owner: root
      group: root
      mode: 0644
    notify:
    - systemd daemon reload
    - update firewall

  - name: make configuration
    template:
      src: templates/gate/etc/nftables/nftables.rules.j2
      dest: "{{ firewall_global.service.rules }}"
      owner: root
      group: root
      mode: 0644
    notify:
      - update firewall

  - name: Enabling firewall service
    service:
      name: firewall
      enabled: yes
