---
- hosts: gate
  remote_user: root
  vars_files:
  - vars/network.yaml
  - vars/pppoe.yaml
  - vars/dhcp.yaml
  - vars/bind.yaml
  - vars/firewall.yaml
  - vars/prometheus.yaml
  - vars/grafana.yaml
  - vars/node_exporter.yaml
  - vars/bind_exporter.yaml
  - vars/ssh_keys.yaml
  - vars/ntpd.yaml
  roles:
  - { role: network_interfaces, tags: network_interfaces }
  - { role: pppoe, tags: pppoe }
  - { role: kernel, tags: kernel }
  - { role: users, tags: users }
  - { role: zsh, tags: zsh }
  - { role: sshd, tags: sshd }
  - { role: journald, tags: journald }
  - { role: bind, tags: bind }
  - { role: dhcp, tags: dhcp }
  - { role: firewall, tags: firewall }
  - { role: ntpd, tags: ntpd }
  - { role: nginx, tags: nginx }
  - { role: prometheus, tags: [ prometheus, monitoring ] }
  - { role: grafana, tags: [ grafana, monitoring ] }
  - { role: node_exporter, tags: [ node_exporter, monitoring ] }
  - { role: bind_exporter, tags: [ bind_exporter, monitoring ] }
  - { role: packages, tags: packages }
