---
- hosts: gate
  remote_user: root
  vars_files:
  - vars/vault.yaml
  - vars/dns.yaml
  - vars/network.yaml
  - vars/ssh_keys.yaml
  - vars/telegram.yaml
  roles:
  - { role: portage, tags: portage }
  - { role: packages, tags: packages }
  - { role: apcupsd, tags: apcupsd }
  - { role: network_interfaces, tags: network_interfaces }
  - { role: gps, tags: gps }
  - { role: pppoe, tags: pppoe }
  - { role: kernel, tags: kernel }
  - { role: users, tags: users }
  - { role: zsh, tags: zsh }
  - { role: sshd, tags: sshd }
  - { role: logrotate, tags: logrotate }
  - { role: journald, tags: journald }
  - { role: bind, tags: bind }
  - { role: dhcp, tags: dhcp }
  - { role: firewall, tags: firewall }
  - { role: ntpd, tags: ntpd }
  - { role: nginx, tags: nginx }
  - { role: prometheus, tags: [ prometheus, monitoring ] }
  - { role: grafana, tags: [ grafana, monitoring ] }
  - { role: node_exporter, tags: [ node_exporter, monitoring ] }
  - { role: bind_exporter, tags: [ bind_exporter, monitoring ] }
  - { role: smartctl_exporter, tags: smartctl_exporter }
  - { role: nftables_exporter, tags: nftables_exporter }
  - { role: mikrotik_exporter, tags: mikrotik_exporter }
  - { role: telegraf, tags: [ telegraf, monitoring ] }
  - { role: tor, tags: tor }
  - { role: 3proxy, tags: 3proxy }
  - { role: observer, tags: observer }
  - { role: htop, tags: htop }
  - { role: minecraft, tags: minecraft }
  - { role: factorio, tags: factorio }
