---
- hosts: gate
  remote_user: root
  vars_files:
  - vars/network.yaml
  - vars/bind.yaml
  - vars/prometheus.yaml
  - vars/sh.yaml

  handlers:
  - import_tasks: handlers/systemd.yaml
  - import_tasks: handlers/motd.yaml

  tasks:

  - name: Install packages
    portage:
      package: "{{ item }}"
      state: present
    with_items:
    - net-dns/bind
    notify:
    - update motd

  - name: Create log directory
    file:
      path: /var/log/named
      state: directory
      owner: named
      group: named
      mode: 0775
    notify:
    - update motd

  - name: Install resolv.conf
    template:
      src: templates/gate/etc/resolv.conf.j2
      dest: /etc/resolv.conf
      owner: root
      group: root
      mode: 0644
    notify:
    - update motd

  - name: Make named configuration
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dst }}"
      owner: root
      group: root
      mode: 0644
    loop:
      - {src: templates/gate/etc/bind/named.conf.j2, dst: /etc/bind/named.conf }
      - {src: templates/gate/etc/bind/pri/domain.local.zones.include.j2, dst: "/etc/bind/pri/{{ networks.home.domain }}.zones.include" }
      - {src: templates/gate/etc/bind/pri/domain.local.zone.j2, dst: "/etc/bind/pri/{{ networks.home.domain }}.zone" }
    notify:
    - restart named
    - update motd

  - name: Enabling services
    service:
      name: named
      enabled: yes
