# - import_playbook: check-ifnames.yaml
- hosts: workstations-linux
  remote_user: root
  vars_files:
  - vars/network.yaml
  - vars/firewall.yaml
  - vars/node_exporter.yaml
  - vars/ssh_keys.yaml
  - vars/ntpd.yaml
  roles:
  # - { role: firewall, tags: firewall }
  - { role: network_interfaces, tags: network_interfaces }
  - { role: kernel, tags: kernel }
  - { role: users, tags: users }
  - { role: zsh, tags: zsh }
  - { role: sshd, tags: sshd }
  - { role: journald, tags: journald }
  - { role: ntp, tags: ntp }
  - { role: node_exporter, tags: [ node_exporter, monitoring ] }
  - { role: packages, tags: packages }
