---
- hosts: gate
  remote_user: root
  vars_files:
  - vars/network.yaml
  - vars/sh.yaml

  handlers:
  - import_tasks: handlers/systemd.yaml
  - import_tasks: handlers/motd.yaml

  tasks:

  - name: Install packages
    portage:
      package: "{{ item }}"
      state: present
    with_items:
    - www-servers/nginx
    notify:
    - update motd

  - name: create dirs for nginx
    file:
      dest: "{{ item }}"
      state: directory
      owner: nginx
    with_items:
      - /etc/nginx/sites
      - /var/log/nginx
    notify:
    - update motd

  - name: deploy nginx configuration
    template:
      owner: nginx
      group: nginx
      src: templates/gate/etc/nginx/nginx.conf.j2
      dest: /etc/nginx/nginx.conf
      mode: 0644
    notify:
    - restart nginx
    - update motd

  - name: Enabling services
    service:
      name: nginx
      enabled: yes
