---
- hosts: gate
  remote_user: root
  vars_files:
  - vars/network.yaml
  - vars/firewall-default.yaml

  handlers:
  - import_tasks: handlers/systemd.yaml

  tasks:
  - name: Install packages
    portage:
      package: "{{ item }}"
      state: present
    with_items:
    - sys-apps/iproute2
    - net-firewall/nftables

  - name: Create conf directory
    file:
      path: /etc/nftables
      state: directory
      owner: root
      group: root
      mode: 0644

  - name: make configuration
    template:
      src: templates/gate/etc/nftables/nftables.rules.j2
      dest: "/etc/nftables/nftables.rules"
      owner: root
      group: root
      mode: 0644
    notify:
      - update firewall

  - name: Enabling firewall service
    service:
      name: nftables-restore
      enabled: yes
