# - import_playbook: check-ifnames.yaml
- hosts: workstations-linux
  remote_user: root
  vars_files:
  - vars/dns.yaml
  - vars/network.yaml
  - vars/ssh_keys.yaml
  - vars/telegram.yaml
  roles:
  # - { role: firewall, tags: firewall }
  - { role: network_interfaces, tags: network_interfaces }
  - { role: smartctl, tags: smartctl }
  - { role: kernel, tags: kernel }
  - { role: users, tags: users }
  - { role: zsh, tags: zsh }
  - { role: sshd, tags: sshd }
  - { role: journald, tags: journald }
  - { role: resolved, tags: resolved }
  - { role: ntp, tags: ntp }
  - { role: node_exporter, tags: [ node_exporter, monitoring ] }
  - { role: telegraf, tags: [ telegraf, monitoring ] }
  - { role: observer, tags: observer }
  - { role: portage, tags: portage }
  - { role: packages, tags: packages }
  - { role: nsswitch, tags: nsswitch }

  # tasks:
  # - name: Sysctl setup
  #   sysctl:
  #     name: "{{ item.key }}"
  #     value: "{{ item.value }}"
  #     state: "{{ item.state|default('present') }}"
  #     sysctl_set: yes
  #     reload: yes
  #   with_items:
  #   - { key: net.ipv6.conf.all.disable_ipv6, value: 0 }
  #   - { key: net.ipv6.conf.default.disable_ipv6, value: 0 }
  #   - { key: net.ipv6.conf.lo.disable_ipv6, value: 0 }
  #   - { key: net.ipv6.conf.default.autoconf, value: 0 }
  #   when: inventory_hostname != 'gate'
