---
- hosts: wpc
  remote_user: root
  vars_files:
  - vars/vault.yaml
  - vars/dns.yaml
  - vars/network.yaml
  - vars/ssh_keys.yaml
  - vars/telegram.yaml
  - vars/network_services.yaml
  roles:
  # - { role: minecraft, tags: minecraft }
  - { role: factorio, tags: factorio }
