---
# - import_playbook: check_ifnames.yaml
- hosts: gate
  remote_user: root
  vars_files:
  - vars/network.yaml

  handlers:
  - import_tasks: handlers/systemd-base.yaml

  tasks:

  - name: Install packages
    portage:
      package: "{{ item }}"
      state: present
    with_items:
    - www-servers/nginx
    - app-metrics/prometheus
    - app-metrics/node_exporter
    - sys-apps/iproute2
    - net-firewall/iptables
    - net-dns/bind
    - net-misc/dhcp
    - net-misc/radvd

  - name: Sysctl setup
    sysctl:
      name: "{{ item.key }}"
      value: "{{ item.value }}"
      state: "{{ item.state|default('present') }}"
      sysctl_set: yes
      reload: yes
    with_items:
    - { key: net.ipv6.conf.all.disable_ipv6,value: 0 }
    - { key: net.ipv6.conf.default.disable_ipv6, value: 0 }
    - { key: net.ipv6.conf.lo.disable_ipv6, value: 0 }
    - { key: net.ipv6.conf.external_rt_0.disable_ipv6, value: 1 }
    - { key: net.ipv4.ip_forward, value: 1 }

  - name: Setup device names
    template:
      src: "templates/{{ inventory_hostname }}/etc/udev/rules.d/00-network.rules.j2"
      dest: /etc/udev/rules.d/00-network.rules
      owner: root
      group: root
      mode: 0644
    notify:
    - restart networkd

  # - debug:
  #     msg: "{{item}}"
  #   with_items:
  #   - "{{ network }}"

  - name: Setup network interface files
    template:
      src: "{{ lookup('first_found', ['templates/{{ inventory_hostname }}/etc/systemd/network/{{ item.ifname }}.network.j2', 'templates/default/etc/systemd/network/static.network.j2']) }}"
      dest: /etc/systemd/network/{{ item.ifname }}.network
      owner: root
      group: root
      mode: 0644
    when: item.mac is defined and
          (
            (item.ip.ipv4 is defined and item.ip.ipv4.type == 'static') or
            (item.ip.ipv6 is defined and item.ip.ipv6.type == 'static')
          )
    with_items:
      - "{{ network }}"
    notify:
    - restart networkd

  - name: Install scripts for firewall save/restore
    template:
      src: "templates/default/usr/local/bin/{{ item }}"
      dest: "/usr/local/bin/{{ item }}"
      owner: root
      group: root
      mode: 0744
    with_items:
    - firewall-load.sh
    - firewall-save.sh
    - firewall-reload.sh
    notify:
    - systemd daemon reload

  - name: Install iptables save/restore service
    template:
      src: templates/default/etc/systemd/system/firewall@.service
      dest: /etc/systemd/system/firewall@.service
      owner: root
      group: root
      mode: 0644
    notify:
    - systemd daemon reload
