---
# - import_playbook: check_ifnames.yaml
- hosts: gate
  remote_user: root
  vars_files:
  - vars/network.yaml

  handlers:
  - import_tasks: handlers/systemd.yaml

  tasks:

  - name: Install packages
    portage:
      package: "{{ item }}"
      state: present
    with_items:
    - www-servers/nginx
    - app-metrics/prometheus
    - app-metrics/node_exporter
    - sys-apps/iproute2
    - net-firewall/iptables
    - net-dns/bind
    - net-misc/dhcp
    # - net-misc/radvd
    # - net-dialup/rp-pppoe

  - name: Sysctl setup
    sysctl:
      name: "{{ item.key }}"
      value: "{{ item.value }}"
      state: "{{ item.state|default('present') }}"
      sysctl_set: yes
      reload: yes
    with_items:
    - { key: net.ipv6.conf.all.disable_ipv6,value: 0 }
    - { key: net.ipv6.conf.default.disable_ipv6, value: 0 }
    - { key: net.ipv6.conf.lo.disable_ipv6, value: 0 }
    - { key: net.ipv6.conf.external_rt_0.disable_ipv6, value: 1 }
    - { key: net.ipv6.conf.all.forwarding, value: 1 }
    - { key: net.ipv6.conf.default.forwarding, value: 1 }
    - { key: net.ipv4.ip_forward, value: 1 }
    - { key: net.ipv4.conf.default.forwarding, value: 1 }


  - name: Setup device names
    template:
      src: "templates/default/etc/udev/rules.d/00-network.rules.j2"
      dest: /etc/udev/rules.d/00-network.rules
      owner: root
      group: root
      mode: 0644
    notify:
    - restart networkd

  - name: Setup network interface files
    include_tasks: tasks/systemd/network/setup-interface.yaml
    loop: "{{ network }}"
    loop_control:
      loop_var: target_interface
