- hosts: workstations-linux
  remote_user: root
  vars_files:
  - vars/network.yaml

  handlers:
  - import_tasks: handlers/systemd.yaml

  tasks:

  - name: Setup device names
    template:
      src: "templates/default/etc/udev/rules.d/00-network.rules.j2"
      dest: /etc/udev/rules.d/00-network.rules
      owner: root
      group: root
      mode: 0644
    notify:
    - restart networkd

  - name: Setup network interface files
    include_tasks: tasks/systemd/network/setup-interface.yaml
    loop: "{{ network }}"
    loop_control:
      loop_var: target_interface
