---
# - hosts: workstations_linux,gate,without_internet
- hosts: pi-game
  remote_user: root
  # gather_facts: False
  # vars_files:
  # - vars/vault.yaml
  # - vars/network.yaml

  tasks:
  - name: Distribution
    debug: msg="{{ ansible_distribution }}"
  - name: Distribution version
    debug: msg="{{ ansible_distribution_version}}"
  - name: Distribution major version
    debug: msg="{{ ansible_distribution_major_version }}"


  # - name: strings
  #   debug:
  #     msg: "{{ arr | map('regex_replace', '(.*)', '\\1_123') | list | join(' ')}}"
  #   vars:
  #     arr:
  #     - qwe
  #     - asd
  #     - zxc

  # - name: Default test
  #   debug:
  #     msg: "Default: {{ ntpd }}"
  #   when: ntpd is defined

  # - name: Merge test
  #   debug:
  #     msg: "Merged: {{ merged_vars.ntpd }}"

  # - name: ship net test
  #   debug:
  #     msg: "{{ query('ship', 'tor_ip', 'ipv4', 1) }}"

  # - name: ship net test
  #   debug:
  #     msg: "{{ query('ship', 'tor_ip', 'ipv6', 1) }}"

  # - name: merge test
  #   debug:
  #     msg: "Merged: {{ hostvars[item].merged_vars.firewall }}\nDefault: {{ hostvars[item].firewall }}"
  #   loop: "{{ hostvars|list }}"

  # - name: ship net test
  #   debug:
  #     msg: "{{ query('ship', 'delegated_net', item).net }} {{ query('ship', 'delegated_net', item).size }}"
  #   loop: "{{ ['ipv6', 'ipv4'] }}"

  # - name: ship net test
  #   debug:
  #     var: networks.home.subnet
