---
# - hosts: workstations_linux,gate,without_internet
- hosts: spc
  remote_user: root
  # gather_facts: False
  # vars_files:
  # - vars/vault.yaml
  # - vars/network.yaml
  vars:
    tf: no

  tasks:
  - debug: msg="got it"
    when: tf
