---
- hosts: spc
  remote_user: root

  tasks:
  - debug:
      msg: "debug"

  - name: portage test
    gentoo_portage:
      name: sys-process/htop
      state: present
      use:
        enabled:
        - unicode
        - lm-sensors
        - hwloc
        disabled:
        - debug
