---
- hosts: gate
  remote_user: root
  vars_files:
  - vars/network.yaml
  - vars/iptables-default.yaml

  handlers:
  - import_tasks: handlers/systemd-base.yaml

  tasks:

  - name: debug addresses
    debug:
      msg: "{{ hostvars['gate'].network|selectattr('ifname', 'match', 'internal.*')|first }}"
