---
- hosts: localhost
  remote_user: root
  vars_files:
  - vars/network.yaml
  - vars/iptables-default.yaml
  vars:
    a: "{{ lookup('ship', 'ip', 22) }}"

  tasks:

  - name: ipv6 test
    debug:
      msg: "{{ item }} is ipv6"
    when: item | ipv6
    loop:
      - 192.168.0.1
      - 100:100::/28
      - "{{ networks.henet.subnet | ipaddr('address') }}"

  - name: ship test
    debug:
      msg: "{{ lookup('ship', 'ip', item).ipv6.format() }} {{ lookup('ship', 'ip', item - 1).ipv4.reverse_dns }}"
    loop: "{{ [11,2,3,4,5,6,7,8,9,22,75, 32] }}"
