---
  - name: Устанавливаем полезные пакеты
    portage:
      package: "{{ item }}"
      state: present
    with_items:
    - app-misc/jq
    - app-admin/sudo
    - app-portage/genlop
    - app-portage/portage-utils
    - app-portage/smart-live-rebuild
    - app-portage/gentoolkit
    - app-portage/euses
    - app-portage/cpuid2cpuflags
    - app-admin/pydf
    - sys-process/htop
    - net-dns/bind-tools
    tags:
    - packages
