---
  - name: "Check for host [{{ target_hostname }}] variables existing"
    stat:
      path: "host_vars/{{ target_hostname }}.yaml"
    delegate_to: "localhost"
    register: host_vars_exist_result

  - name: "Setting host [{{ target_hostname }}] variables existing fact"
    set_fact:
      target_hostvars_exists: host_vars_exist_result.stat.exists

  - name: "Loading host [{{ target_hostname }}] variables"
    include_vars:
      file: "host_vars/{{ target_hostname }}.yaml"
      name: target_hostvars
    when: target_hostvars_exists
