---
  - name: Устанавливаем необходимые пакеты
    include_role:
      name: portage
      tasks_from: install_package
    vars:
      package: "{{ item }}"
    loop:
    - { name: x11-misc/lightdm, use: { enabled: [gtk, introspection, qt5, vala], disabled: [gnome, audit] }}
    - { name: media-fonts/emojione-color-font, unstable: yes }
    - { name: media-fonts/twemoji-color-font, unstable: yes }
    - { name: x11-themes/qtcurve, use: { enabled: [gtk, nls, qt5] } }
    - { name: x11-themes/comix-xcursors, use: { enabled: [opaque], disabled: [lefthanded] } }
    - { name: media-fonts/ubuntu-font-family }
    - { name: x11-misc/qt5ct, unstable: no, x86_as_amd64: yes }
    - { name: x11-themes/gtk-chtheme }
    tags:
    - packages

  - debug:
      msg: '{{ merged_vars.xorg }}'

  - name: Устанавливаем конфиги xorg
    template:
      src: "etc/X11/xorg.conf.d/{{ i_xorg_conf }}.j2"
      dest: "/etc/X11/xorg.conf.d/{{ i_xorg_conf }}"
      mode: 0644
    loop:
    - 32_devices.conf
    loop_control:
      loop_var: i_xorg_conf

  - name: Устанавливаем конфиги DM
    template:
      src: "{{ i_dm_conf }}.j2"
      dest: "/{{ i_dm_conf }}"
      mode: 0644
    loop:
    - etc/sddm.conf
    - etc/lightdm/lightdm.conf
    loop_control:
      loop_var: i_dm_conf

  - name: Устанавливаем xrandr скрипт
    template:
      src: usr/local/bin/xrandrapply.j2.sh
      dest: /usr/local/bin/xrandrapply.sh
      mode: 0755
    when: merged_vars.xorg.monitors | length > 1

  - name: Деплоим в юзера
    include_tasks: user_part.yaml
    loop: "{{ users }}"
    loop_control:
      loop_var: i_user
    when: i_user.name != 'root'
