---
  - name: Устанавливаем необходимые пакеты
    include_role:
      name: portage
      tasks_from: install_package
    vars:
      package: "{{ item }}"
    loop:
    - { name: sys-firmware/nvidia-firmware }
    # - { name: x11-drivers/xf86-video-nouveau }
    tags:
    - packages
