---
  - name: Устанавливаем необходимые пакеты
    include_role:
      name: portage
      tasks_from: install_package
    vars:
      package: "{{ item }}"
    loop:
    - { name: media-sound/pulseaudio, use: { enabled: [alsa, alsa-plugin, bluetooth, ipv6, systemd, equalizer, udev, asyncns, webrtc-aec, libsamplerate], disabled: [gconf, lirc] } }
    - { name: media-plugins/calf, use: { enabled: [lv2] } }
    - { name: media-sound/pulseeffects, use: { enabled: [bs2b, calf, mda-lv2, rubberband] } }
    - { name: media-sound/pamix }
    - { name: media-sound/pasystray, unstable: yes }
    - { name: media-sound/pavucontrol }
    - { name: media-sound/pavumeter }
    - { name: media-sound/pavucontrol-qt }
    tags:
    - packages

  - name: Устанавливаем конфиги
    template:
      src: "{{ item }}.j2"
      dest: "/{{ item }}"
      owner: root
      group: root
      mode: 0644
    loop:
    - etc/pulse/client.conf
    - etc/pulse/daemon.conf
    - etc/pulse/default.pa
    - etc/pulse/system.pa
