---
  debug: no

  formatter:
    templates_path: ./templates

  output:
    telegram:
      token: '595129902:AAEmDHkEDFDFIMhL3wt6fq_HmEyEmR8mfoc'
      targets:
      - name: Observers
        destination:
          rooms:
          - '-1001278522486'

  input:
    journald:
      rules:
      - name: new_session
        match:
          positive: '^.*Started Session (?P<session_id>.+?) of user (?P<user>.+?)\.$'
          negative: ''
        outputs:
        - Observers
      - name: interface_status
        match:
          positive: '^.*kernel: .+? internal_0: (?P<event>.+?)$'
          negative: ''
        outputs:
        - Observers
    logfile:
      positions_file: /tmp/observer.logfiles.positions
      rules:
      - name: test
        identifier: sometest
        match:
          positive: '^.*test (?P<one>.+?) (?P<two>.+?) test.*$'
          negative: 'foo'
        path: /var/log/test.log
        store_position: False
        outputs:
        - Observers
