---
  node_exporter:
    textfile_dir: /var/lib/node_exporter/textfile_collector
    listen:
      port: 9100
    collectors:
      enabled:
      - arp
      - buddyinfo
      - conntrack
      - cpu
      - cpufreq
      - diskstats
      - entropy
      - filefd
      - filesystem
      - hwmon
      - loadavg
      - logind
      - meminfo
      - meminfo_numa
      - mountstats
      - netclass
      - netdev
      - netstat
      - powersupplyclass
      - sockstat
      - stat
      - systemd
      - tcpstat
      - textfile
      - thermal_zone
      - time
      - uname
      - vmstat

  node_exporter_all_collectors:
  - arp
  - bcache
  - bonding
  - btrfs
  - buddyinfo
  - conntrack
  - cpu
  - cpufreq
  - diskstats
  - drbd
  - edac
  - entropy
  - fibrechannel
  - filefd
  - filesystem
  - hwmon
  - infiniband
  - interrupts
  - ipvs
  - ksmd
  - loadavg
  - logind
  - mdadm
  - meminfo
  - meminfo_numa
  - mountstats
  - netclass
  - netdev
  - netstat
  - network_route
  - nfs
  - nfsd
  - ntp
  - perf
  - powersupplyclass
  - pressure
  - processes
  - qdisc
  - rapl
  - runit
  - schedstat
  - sockstat
  - softnet
  - stat
  - supervisord
  - systemd
  - tcpstat
  - textfile
  - thermal_zone
  - time
  - timex
  - udp_queues
  - uname
  - vmstat
  - wifi
  - xfs
  - zfs
  - zoneinfo

  dist_difference:
    node_exporter:
      user:
        Ubuntu: prometheus
        Debian: prometheus
        Gentoo: node_exporter
      binary_path:
        Ubuntu: /usr/bin/prometheus-node-exporter
        Debian: /usr/bin/prometheus-node-exporter
        Gentoo: /usr/sbin/node_exporter
