---
  kernel:
    genkernel:
      enabled: yes
      options:
      - btrfs
      - no-zfs
      - no-lvm
      - no-dmraid
      - no-luks

  zsh:
    theme: "gentoo"
    plugins:
    - git
    - ssh-agent

  node_exporter:
    collectors:
      enabled:
      - btrfs
      - interrupts
      - mdadm