---
  portage:
    directoryes:
      portdir: /usr/portage
      distdir: /storage/hdd/portage/distfiles
      pkgdir: /storage/hdd/portage/packages
      tmp: /storage/hdd/tmp

    use:
      enabled:
        filesystems:
        - btrfs
        hardware:
        - mdadm
        - hamlib
        - radio
        - rtlsdr
      disabled:
        network:
        - wifi
    hardware:
      abi:
        need_32_on_64: yes
      video_cards:
      - nvidia
