---
  Xorg:
    options:
      dpi: 96
      init_order:
      - center
      - top
      - left
      - right
    videocards:
      first:
        name: "NVIDIA Corporation GP107 [GeForce GTX 1050 Ti]"
        pci: "01:00.0"
    monitors:
      center:
        name: "LG 22MP55"
        video_out: "HDMI-0"
        position:
          base: yes
        mode:
          width: 1920
          height: 1080
          rate: 60
      left:
        name: "LG L1740BQ"
        video_out: "HDMI-1"
        position:
          where: left-of
          from: center
        mode:
          width: 1280
          height: 1024
          rate: 60
      right:
        name: "LG L1740PQ"
        video_out: "DP-1"
        position:
          where: right-of
          from: center
        mode:
          width: 1280
          height: 1024
          rate: 60
      top:
        name: "ViewSonic WX2235WM-EU"
        video_out: "DVI-D-0"
        position:
          where: above
          from: center
        mode:
          width: 1680
          height: 1050
          rate: 60
