---
  - name: Устанавливаем необходимые пакеты
    include_role:
      name: portage
      tasks_from: install_package
    vars:
      package: { name: dev-java/oracle-jre-bin, use: { disabled: [fontconfig, nsplugin, alsa, javafx], enabled: [headless-awt] } }
    tags:
    - packages

  - name: Добавляем пользователя
    import_role:
      name: system_user
      tasks_from: setup_user
    vars:
      user:
        name: "{{ merged_vars.minecraft.user.name }}"
        password: "{{ merged_vars.minecraft.user.pw  }}"
        comment: Minecraft runner
        groups:
        - users

  - name: Создаём каталоги
    file:
      dest: "{{ item }}"
      state: directory
      owner: "{{ merged_vars.minecraft.user.name }}"
      group: "{{ merged_vars.minecraft.user.name }}"
      mode: 0755
    loop:
    - "{{ merged_vars.minecraft.paths.home }}"
    - "{{ merged_vars.minecraft.paths.log }}"

  - name: Определяем переменные
    set_fact:
      f_version_manifest_file: "/tmp/minecraft_version_manifest.json"
      f_version_file: "/tmp/minecraft_version.json"
      f_java_options: "-XX:{{ merged_vars.minecraft.java_options | join(' -XX:') }}"

  - name: Выкачиваем инфо о версиях
    get_url:
      url: https://launchermeta.mojang.com/mc/game/version_manifest.json
      dest: "{{ f_version_manifest_file }}"
      mode: 0644
      force: yes
    check_mode: no
    delegate_to: localhost

  - name: Выкачиваем инфо текущего релиза
    get_url:
      url: "{{ v_release_json_url }}"
      dest: "{{ f_version_file }}"
      mode: 0644
      force: yes
    check_mode: no
    delegate_to: localhost
    vars:
      v_json_string: "{{ lookup('file', f_version_manifest_file) }}"
      v_latest_release: "{{ v_json_string | json_query('latest.release') }}"
      v_json_url_query: "versions[?id=='{{ v_latest_release }}'].url"
      v_release_json_url: '{{ v_json_string | json_query(v_json_url_query) | first }}'

  - name: Выкачиваем minecraft сервер
    get_url:
      url: "{{ v_url }}"
      dest: "{{ merged_vars.minecraft.paths.home }}/server.jar"
      mode: 0644
      owner: "{{ merged_vars.minecraft.user.name }}"
      checksum: "sha1:{{ v_hash }}"
    vars:
      v_json_string: "{{ lookup('file', f_version_file) }}"
      v_url: "{{ v_json_string | json_query('downloads.server.url') }}"
      v_hash: "{{ v_json_string | json_query('downloads.server.sha1') }}"
    notify:
    - restart minecraft

  - name: Генерируем конфиг сервера
    lineinfile:
      path: "/opt/minecraft/server.properties"
      regexp: "^{{ item.name }}="
      line: "{{ item.name }}={{ item.value }}"
    loop:
    - { name: 'allow-cheats',                  value: '{{ merged_vars.minecraft.options.cheats                  |    string | lower }}'  }
    - { name: 'allow-flight',                  value: '{{ merged_vars.minecraft.options.players.flight          |    string | lower }}'  }
    - { name: 'allow-nether',                  value: '{{ merged_vars.minecraft.options.game.dimensions.nether  |    string | lower }}'  }
    - { name: 'broadcast-console-to-ops',      value: 'true'                                                                             }
    - { name: 'broadcast-rcon-to-ops',         value: 'true'                                                                             }
    - { name: 'debug',                         value: '{{ merged_vars.minecraft.debug                           |    string | lower }}'  }
    - { name: 'difficulty',                    value: '{{ merged_vars.minecraft.options.game.difficulty                             }}'  }
    - { name: 'enable-command-block',          value: '{{ merged_vars.minecraft.options.game.command_block      |    string | lower }}'  }
    - { name: 'enable-query',                  value: '{{ merged_vars.minecraft.network.query.enabled           |    string | lower }}'  }
    - { name: 'enable-rcon',                   value: '{{ merged_vars.minecraft.network.rcon.enabled            |    string | lower }}'  }
    - { name: 'force-gamemode',                value: 'true'                                                                             }
    - { name: 'gamemode',                      value: '{{ merged_vars.minecraft.options.game.gamemode                               }}'  }
    - { name: 'generate-structures',           value: '{{ merged_vars.minecraft.options.spawn.structures        |    string | lower }}'  }
    - { name: 'generator-settings',            value: ''                                                                                 }
    - { name: 'hardcore',                      value: '{{ merged_vars.minecraft.options.game.hardcore           |    string | lower }}'  }
    - { name: 'level-name',                    value: '{{ merged_vars.minecraft.options.world.level_name                            }}'  }
    - { name: 'level-seed',                    value: '{{ merged_vars.minecraft.options.world.seed                                  }}'  }
    - { name: 'level-type',                    value: '{{ merged_vars.minecraft.options.game.level_type                             }}'  }
    - { name: 'max-build-height',              value: '{{ merged_vars.minecraft.options.world.size.height                           }}'  }
    - { name: 'max-players',                   value: '{{ merged_vars.minecraft.options.players.maximum                             }}'  }
    - { name: 'max-tick-time',                 value: '-1'                                                                               }
    - { name: 'max-world-size',                value: '{{ merged_vars.minecraft.options.world.size.side                             }}'  }
    - { name: 'motd',                          value: '{{ merged_vars.minecraft.options.world.motd                                  }}'  }
    - { name: 'network-compression-threshold', value: '{{ merged_vars.minecraft.network.compression_threshold                       }}'  }
    - { name: 'online-mode',                   value: '{{ merged_vars.minecraft.options.players.registered_only|     string | lower }}'  }
    - { name: 'op-permission-level',           value: '4'                                                                                }
    - { name: 'player-idle-timeout',           value: '0'                                                                                }
    - { name: 'prevent-proxy-connections',     value: 'false'                                                                            }
    - { name: 'pvp',                           value: '{{ merged_vars.minecraft.options.players.pvp             |    string | lower }}'  }
    - { name: 'query.port',                    value: '{{ merged_vars.minecraft.network.query.port                                  }}'  }
    - { name: 'rcon.password',                 value: '{{ merged_vars.minecraft.network.rcon.pw                                     }}'  }
    - { name: 'rcon.port',                     value: '{{ merged_vars.minecraft.network.rcon.port                                   }}'  }
    - { name: 'resource-pack-sha1',            value: ''                                                                                 }
    - { name: 'resource-pack',                 value: ''                                                                                 }
    - { name: 'server-ip',                     value: ''                                                                                 }
    - { name: 'server-port',                   value: '{{ merged_vars.minecraft.network.port                                        }}'  }
    - { name: 'snooper-enabled',               value: '{{ merged_vars.minecraft.network.send_stat_to_devs       |    string | lower }}'  }
    - { name: 'spawn-animals',                 value: '{{ merged_vars.minecraft.options.spawn.animals           |    string | lower }}'  }
    - { name: 'spawn-monsters',                value: '{{ merged_vars.minecraft.options.spawn.monsters          |    string | lower }}'  }
    - { name: 'spawn-npcs',                    value: '{{ merged_vars.minecraft.options.spawn.npcs              |    string | lower }}'  }
    - { name: 'spawn-protection',              value: '0'                                                                                }
    - { name: 'use-native-transport',          value: 'true'                                                                             }
    - { name: 'view-distance',                 value: '{{ merged_vars.minecraft.options.world.size.view                             }}'  }
    - { name: 'white-list',                    value: '{{ merged_vars.minecraft.options.players.whitelisted     |    string | lower }}'  }

  - name: Генерируем конфиги
    template:
      src: "opt/minecraft/{{ item }}.j2"
      dest: "/opt/minecraft/{{ item }}"
      owner: "{{ merged_vars.minecraft.user.name }}"
      group: "{{ merged_vars.minecraft.user.name }}"
      mode: 0644
    loop:
    - whitelist.json
    - ops.json
    - banned-ips.json
    - banned-players.json
    - eula.txt
    notify:
    - restart minecraft

  - name: Устанавливаем сервис
    import_role:
      name: systemd_unit
      tasks_from: setup_service
    vars:
      service:
        name: minecraft
        description: Minecraft daemon
        restart_sec: 32s
        working_dir: "{{ merged_vars.minecraft.paths.home }}"
        environments:
        - { name: MINECRAFT_JAVA_MAX_MEMORY, value: "{{ merged_vars.minecraft.memory.max }}" }
        - { name: MINECRAFT_JAVA_INITIAL_MEMORY, value: "{{ merged_vars.minecraft.memory.initial }}" }
        - { name: MINECRAFT_JAVA_HEAP_YOUNG_GEN_MEMORY, value: "{{ merged_vars.minecraft.memory.heap_young_gen }}" }
        - { name: MINECRAFT_JAVA_THREAD_STACK_SIZE_MEMORY, value: "{{ merged_vars.minecraft.memory.thread_stack_size }}" }
        - { name: MINECRAFT_JAVA_OPTIONS, value: "{{ f_java_options }}" }
        exec_start: >
          /bin/sh -c "
          /usr/bin/java
          -server -d64
          -Xmx${MINECRAFT_JAVA_MAX_MEMORY}
          -Xms${MINECRAFT_JAVA_INITIAL_MEMORY}
          -Xss${MINECRAFT_JAVA_THREAD_STACK_SIZE_MEMORY}
          -Xmn${MINECRAFT_JAVA_HEAP_YOUNG_GEN_MEMORY}
          ${MINECRAFT_JAVA_OPTIONS}
          -jar {{ merged_vars.minecraft.paths.home }}/server.jar nogui "
        user: "{{ merged_vars.minecraft.user.name }}"
        group: "{{ merged_vars.minecraft.user.name }}"
        after:
        - network-online.target
        wanted_by:
        - multi-user.target
        on_changed: "{{ 'restarted' if merged_vars.minecraft.active else 'noop' }}"
        state: "{{ 'started' if merged_vars.minecraft.active else 'stopped' }}"
        enabled: "{{ merged_vars.minecraft.active }}"
