---
  - name: Устанавливаем необходимые пакеты
    include_tasks: "{{ ansible_distribution }}/packages.yaml"
    tags:
    - packages

  - name: Установка пользователя
    import_role:
      name: system_user
      tasks_from: setup_user
    vars:
      user:
        name: rtspserver
        comment: v4l2-rtsp daemon runner
        groups:
        - users
        - video

  - name: Цикл по камерам
    include_tasks: camera.yaml
    loop: "{{ v4l2rtspserver_cameras }}"
    loop_control:
      loop_var: i_camera
