---
  - name: "{{ lr.name }} : Деплоим конфиг ротации"
    template:
      src: etc/logrotate.d/template.j2
      dest: "/etc/logrotate.d/{{ lr.name }}"
      owner: root
      group: root
      mode: 0644
