---
  - name: restart all streams
    systemd:
      name: "stream-to-m3u8-{{ i_camera }}"
      state: restarted
    loop: "{{ groups.cameras }}"
    loop_control:
      loop_var: i_camera
    when: "'stream_paths' in hostvars[i_camera].merged_vars"
