---
  - name: systemd daemon reload
    systemd:
      daemon_reload: yes

  - name: restart pppoe@rt
    systemd:
      name: pppoe@rt
      state: restarted

  - name: restart pppoe
    systemd:
      name: "pppoe@{{ item }}"
      state: restarted
    loop: "{{ pppoe.providers }}"
