---
  - name: systemd daemon reload
    shell: systemctl daemon-reload

  - name: restart pppoe@rt
    service:
      name: pppoe@rt
      state: restarted

  - name: restart pppoe
    service:
      name: "pppoe@{{ item }}"
      state: restarted
    loop: "{{ pppoe.providers }}"
