---
  # - name: "Debug [{{ target_host }}]"
  #   debug:
  #     msg: "{{hostvars[target_host]}}"

  # - include_tasks: tasks/iptables/host-rules.yaml
  #   loop: "{{ query('inventory_hostnames', target_group)|difference(['gate']) }}"
  #   loop_control:
  #     loop_var: target_host

  - name: Check for group [target_group] variables existing
    stat:
      path: /etc/file.txt
    delegate_to: "localhost"
    register: group_vars_exist_result

  - name: Loading group [target_group] variables
    include_vars:
      file: "group_vars/{{ target_group }}.yaml"
      name: groupvars
    when: group_vars_exist_result.stat.exists

  - include_tasks: tasks/iptables/group-host-rules.yaml
    loop: "{{ groupvars.iptables.host_to_internet }}"
    when: group_vars_exist_result.stat.exists            and
          groupvars.iptables                  is defined and
          groupvars.iptables.host_to_internet is defined
    loop_control:
      loop_var: target_rule
