---
  - include_tasks: tasks/loading_variables/load-group-vars.yaml

  - name: "Setting group-to-host [{{ target_groupname }}] variables fact"
    set_fact:
      target_hostvars: "{{ target_groupvars }}"
      target_hostvars_exists: "{{ target_groupvars_exists }}"
    when: target_groupvars_exists

  - name: "Set group->internet [{{ target_groupname }}] rules"
    include_tasks: tasks/iptables/host-to-internet.yaml
    loop: "{{ query('inventory_hostnames', target_groupname)|difference(['gate']) }}"
    loop_control:
      loop_var: target_hostname
    when: target_groupvars_exists

  # - name: "Set group->gate [{{ target_group }}] rules"
  #   include_tasks: tasks/iptables/group-host-rules.yaml
  #   loop: "{{ alone_group_vars.iptables.host_to_gate }}"
  #   when: group_vars_exist_result.stat.exists               and
  #         alone_group_vars.iptables              is defined and
  #         alone_group_vars.iptables.host_to_gate is defined
  #   loop_control:
  #     loop_var: target_rule
