---
  - name: "Iptables network->internet rule"
    iptables:
      chain: OUTPUT
      jump:             "{{ item.1.policy | default('ACCEPT') }}"
      ip_version:       "{{ item.3 }}"
      protocol:         "{{ item.4 }}"
      destination_port: "{{ item.1.ports | default('0:65535') }}"
      comment:          "[{{ item.2 }}->internet] {{ item.1.name }} [{{ item.4 }}:{{ item.3 }}]"
      destination:      "{{ (item.1.destination|default(['0.0.0.0/0', '::/0']))|select('search', '\\:' if item.3 == 'ipv6' else '\\.')|list|join(',') }}"
      source:           "{{ item.2 }}"
      out_interface:    "{{ item.0.ifname }}"
      match:            ["multiport"]
      # in_interface:     "{{ (hostvars['gate'].network|selectattr('ifname', 'match', 'internal.*')|first).ifname }}"
    when: (
            (":" in item.2 and item.3 == 'ipv6') or
            ("." in item.2 and item.3 == 'ipv4')
          )
    notify:
    - "restart iptables.{{ item.3 }}"
    - finish iptables rules
    with_nested:
    - "{{ hostvars['gate'].network|selectattr('ifname', 'match', 'external.*')|list }}"
    - "{{ global_vars.iptables.host_to_internet }}"
    - "{{ [networks.home.subnet+'/'+networks.home.mask.short|string, networks.henet.subnet+'/'+networks.henet.mask.short|string] }}"
    - [ 'ipv6', 'ipv4' ]
    - [ 'tcp', 'udp' ]
