---
  - name: systemd daemon reload
    systemd:
      daemon_reload: yes

  - name: restart dhcpd
    systemd:
      name: "dhcpd@{{ item }}"
      state: restarted
    loop:
      - 6
      - 4

  - name: restart dhcpd@4
    systemd:
      name: dhcpd@4
      state: restarted

  - name: restart dhcpd@6
    systemd:
      name: dhcpd@6
      state: restarted

  - name: restart radvd
    systemd:
      name: radvd
      state: restarted
