---
  - name: systemd daemon reload
    shell: systemctl daemon-reload

  - name: restart dhcpd
    service:
      name: "dhcpd@{{ item }}"
      state: restarted
    loop:
      - 6
      - 4

  - name: restart dhcpd@4
    service:
      name: dhcpd@4
      state: restarted

  - name: restart dhcpd@6
    service:
      name: dhcpd@6
      state: restarted

  - name: restart radvd
    service:
      name: radvd
      state: restarted
