---
  network:
  - name: "Internal ethernet"
    ifname: "internal_0"
    dns:
      aliases:
        - flsun
        - flsun_onvif
        - octoprint
    mac: "dc:a6:32:ec:a9:45"
    duid: "00:02:00:00:ab:11:ef:54:e7:a7:4e:21:17:2a"
    ip: "{{ query('ship', 'ip', 42) | first }}"
    network: 'home'
    type: 'dhcp'

  # - name: "Internal wifi"
  #   ifname: "internal_wifi_0"
  #   mac: "dc:a6:32:ec:a9:46"
  #   # duid: "00:02:00:00:ab:11:47:f9:ac:16:b7:b3:a2:d7"
  #   ip: "{{ query('ship', 'ip', 43) | first }}"
  #   network: 'home'
  #   type: 'dhcp'
