---
  - name: Выливаем лого
    win_copy:
      src: "logo/{{ merged_vars.windows.oem.logo.name }}.bmp"
      dest: "{{ merged_vars.windows.oem.logo.location }}"

  - name: Применяем OEM
    win_regedit:
      path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\OEMInformation'
      name: '{{ item.name }}'
      data: '{{ item.data }}'
      state: present
    loop:
    - { name: 'Logo'        , data: "{{ merged_vars.windows.oem.logo.location }}" }
    - { name: 'Manufacturer', data: "{{ merged_vars.windows.oem.manufacturer }}"  }
    - { name: 'Model'       , data: "{{ merged_vars.windows.oem.model }}"         }
    - { name: 'SupportHours', data: "{{ merged_vars.windows.oem.support.hours }}" }
    - { name: 'SupportPhone', data: "{{ merged_vars.windows.oem.support.phone }}" }
    - { name: 'SupportURL'  , data: "{{ merged_vars.windows.oem.support.url }}"   }
