---
  grub2:
    video:
      vga: '0x31a'
      resolution: '1280x1024'
      colorbits: '16'
      uefi: yes
    kernel:
      options:
      - 'mitigations=off'
    boot:
      #device: "/dev/sda1"
      device: "LABEL=efi-boot"
      fs: "btrfs"
