---
  factorio:
    active: yes
    version: 0.18.31
    user:
      name: factorio
      pw: "{{ factorio_secrets.system_user_pw }}"
    port: 3192
    paths:
      home: /opt/factorio
    server:
      name: "Babylon 5"
      description: "Sheridan personal factorio server"
      password: "{{ factorio_secrets.server_password }}"
      max_players: 16
      auto_pause: yes
      autosave:
        interval: 8
        slots: 512
      visibility:
        public: yes,
        lan: yes
      auth:
        login: "{{ factorio_secrets.auth.login }}"
        password: "{{ factorio_secrets.auth.password }}"
      admins:
      - Sheridan
    mods:
      - name: blueprint_flip_and_turn
        version: latest
      - name: Enhanced_Map_Colors
        version: latest
      - name: LightCone
        version: latest
      - name: Soundpack-alerts-and-sirens
        version: latest
      - name: NightvisionToggles
        version: latest
      - name: Turbwhine
        version: latest
      - name: JKIL-CarLight
        version: latest
      # - name: factoryplanner
      #   version: latest
