---
  factorio:
    active: yes
    version: 1.1.97
    user:
      name: factorio
      pw: "{{ factorio_secrets.system_user_pw }}"
    port: 3192
    paths:
      home: /opt/factorio
    server:
      name: "Babylon 5"
      description: "Sheridan personal factorio server"
      password: "{{ factorio_secrets.server_password }}"
      max_players: 16
      auto_pause: yes
      autosave:
        interval: 8
        slots: 512
      visibility:
        public: yes
        lan: yes
      auth:
        login: "{{ factorio_secrets.auth.login }}"
        password: "{{ factorio_secrets.auth.password }}"
      admins:
      - Sheridan
    mods:
      # base
      - name: flib
        version: latest
      # resources
      - name: HallOfFame
        version: latest
      - name: factoriohd_modpack
        version: latest
      ## icons
      - name: SchallVirtualSignal
        version: latest
      - name: emoji-signals
        version: latest
      - name: snouz-useful-icons
        version: latest
      - name: Kux-VirtualSignals
        version: latest
      - name: more_circuit_signals_UPDATED
        version: latest
      ## sounds
      - name: Soundpack-alerts-and-sirens-updated-v1-1
        version: latest
      - name: Turbwhine
        version: latest
      - name: Ki_Alerts
        version: latest
      # visual
      ## light
      - name: BigLight
        version: latest
      - name: darker-lamp
        version: latest
      - name: RealisticFlashlight
        version: latest
      - name: custom-map-colors
        version: latest
      - name: CustomColor
        version: latest
      ## character
      - name: GirlCharacter
        version: latest
      ## ui
      - name: AlertsList2
        version: latest
      - name: alert-center
        version: latest
      - name: BetterAlertArrows
        version: latest
      - name: Shortcuts-ick
        version: latest
      - name: SchallEntityInspector
        version: latest
      - name: showTileGridLite
        version: latest
      # stats
      - name: StatsGui
        version: latest
      # - name: train-log
      #   version: latest
      - name: SchallSatelliteController
        version: latest
      - name: production-analyst
        version: latest
      # QoL
      - name: Spidertron-Inventory-Sorter
        version: latest
      - name: inventory-templates
        version: latest
      - name: personal-logistics-templates
        version: latest
      - name: QuickbarTemplates
        version: latest
      # - name: TagBook
      #   version: latest
      - name: AutoDeconstruct
        version: latest
      # - name: ordered-rich-text-train-stops
      #   version: latest
      # - name: AutoTrash
      #   version: latest
      # - name: blueprint-request
      #   version: latest
      - name: LogisticRequestManager
        version: latest
      - name: spidertron-control-center
        version: latest
      - name: Automatic_Train_Painter
        version: latest
      # planners
      - name: WellPlanner
        version: latest
      - name: mining-patch-planner
        version: latest
      # calc
      - name: solar-calc
        version: latest
      - name: calculator-ui
        version: latest
      # information
      - name: RecipeBook
        version: latest
      # tools
      # - name: blueprint_flip_and_turn
      #   version: latest
      - name: BlueprintTools
        version: latest
      # - name: DestructiveBlueprints
      #   version: latest
      # - name: redo
      #   version: latest
