---
  - name: Устанавливаем свой ntp сервер
    win_regedit:
      path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\DateTime\Servers
      name: 1
      data: "ntp.{{ networks.home.domain }}"

  - name: Устанавливаем прочие ntp сервера
    win_regedit:
      path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\DateTime\Servers
      name: "{{ idx + 2 }}"
      data: "{{ item }}"
    loop: "{{ merged_vars.ntpd.servers }}"
    loop_control:
      index_var: idx
