---
  - name: Устанавливаем необходимые пакеты
    include_role:
      name: portage
      tasks_from: install_package
    vars:
      package: "{{ item }}"
    loop:
    - { name: app-shells/zsh }
    - { name: app-shells/zsh-completions }
    - { name: app-shells/gentoo-zsh-completions }
