---
  - name: systemd daemon reload
    shell: systemctl daemon-reload

  - name: restart networkd
    service:
      name: systemd-networkd
      state: restarted

  - name: restart dhcpd
    service:
      name: "dhcpd@{{ item }}"
      state: restarted
    loop:
      - 6
      - 4

  - name: restart radvd
    service:
      name: radvd
      state: restarted

  - name: restart named
    service:
      name: named
      state: restarted

  - name: reload firewall
    service:
      name: "firewall@{{ item }}"
      state: reloaded
    loop:
      - 6
      - 4

  - name: restart prometheus
    service:
      name: prometheus
      state: restarted

  - name: restart gate prometheus
    service:
      name: prometheus
      state: restarted
    delegate_to: gate

  - name: restart grafana
    service:
      name: grafana
      state: restarted

  - name: restart node_exporter
    service:
      name: node_exporter
      state: restarted

  - name: restart bind_exporter
    service:
      name: bind_exporter
      state: restarted

  - name: reload nginx
    service:
      name: nginx
      state: reloaded

  - name: restart nginx
    service:
      name: nginx
      state: restarted

  - name: restart pppoe@rt
    service:
      name: pppoe@rt
      state: restarted

  - name: restart pppoe
    service:
      name: "pppoe@{{ item }}"
      state: restarted
    loop: "{{ pppoe.providers }}"
