---
  - name: systemd daemon reload
    shell: systemctl daemon-reload

  - name: restart networkd
    service:
      name: systemd-networkd
      state: restarted

  - name: restart dhcpd
    service:
      name: dhcpd
      state: restarted

  - name: restart named
    # debug:
    #   msg: restarted
    service:
      name: named
      state: restarted
