---
  - name: systemd daemon reload
    shell: systemctl daemon-reload

  - name: restart networkd
    service:
      name: systemd-networkd
      state: restarted

  - name: restart pppoe@rt
    service:
      name: pppoe@rt
      state: restarted

  - name: restart pppoe
    service:
      name: "pppoe@{{ item }}"
      state: restarted
    loop: "{{ pppoe.providers }}"

  - name: restart sshd
    service:
      name: sshd
      state: restarted

  - name: restart journald
    service:
      name: systemd-journald
      state: restarted
