---
  network:
  - name: "Internal"
    ifname: "internal_0"
    #mac: "94:de:80:7c:8b:ee"
    mac: "a8:a1:59:88:94:e3"
    duid: "00:02:00:00:ab:11:bf:7a:de:59:6e:f4:75:1e"
    ip: "{{ query('ship', 'ip', 10) | first }}"
    network: 'home'
    type: 'dhcp'

  # ansible_host: "{{ network.ip.ipv4.ip }}"
