---
  - name: Устанавливаем необходимые пакеты
    include_role:
      name: portage
      tasks_from: install_package
    vars:
      package: "{{ item }}"
    loop:
    - { name: net-firewall/iptables, state: absent }
    - { name: net-firewall/nftables }
    - { name: sys-apps/iproute2 }
    tags:
    - packages

  - name: Настройка sysctl
    sysctl:
      name: "{{ item.key }}"
      value: "{{ item.value }}"
      state: "{{ item.state|default('present') }}"
      sysctl_set: yes
      reload: yes
    with_items:
    - { key: net.ipv6.conf.all.disable_ipv6, value: 0 }
    - { key: net.ipv6.conf.default.disable_ipv6, value: 0 }
    - { key: net.ipv6.conf.lo.disable_ipv6, value: 0 }
    - { key: net.ipv6.conf.bridge_rt_0.disable_ipv6, value: 1 }
    - { key: net.ipv6.conf.all.forwarding, value: 1 }
    - { key: net.ipv6.conf.default.forwarding, value: 1 }
    - { key: net.ipv4.ip_forward, value: 1 }
    - { key: net.ipv4.conf.default.forwarding, value: 1 }
    - { key: net.ipv4.conf.all.log_martians, value: 0 }
    - { key: net.ipv4.conf.default.log_martians, value: 0 }
    - { key: net.ipv4.conf.all.route_localnet, value: 1 }
    - { key: net.ipv4.conf.default.route_localnet, value: 1 }
    when: inventory_hostname == 'gate'

  - name: Создание каталога для настроек
    file:
      path: "{{ config.location }}"
      state: directory
      owner: root
      group: root
      mode: 0644

  - name: Установка скриптов управления стеной
    template:
      src: usr/local/bin/firewall-manager.sh.j2
      dest: /usr/local/bin/firewall-manager.sh
      owner: root
      group: root
      mode: 0744
    notify:
    - update firewall

  - name: Установка скриптов управления маршрутами
    template:
      src: usr/local/bin/route-tables-reload.sh.j2
      dest: /usr/local/bin/route-tables-reload.sh
      owner: root
      group: root
      mode: 0744

  - name: Установка конфигурации firewall'а
    template:
      src: etc/nftables/nftables.rules.j2
      dest: "{{ config.location }}/{{ config.filename }}"
      owner: root
      group: root
      mode: 0644
    notify:
    - update firewall

  - name: Установка конфигурации iproute2
    template:
      src: etc/iproute2/rt_tables.j2
      dest: /etc/iproute2/rt_tables
      owner: root
      group: root
      mode: 0644

  - name: Установка сервиса firewall'а
    import_role:
      name: systemd_unit
      tasks_from: setup_service
    vars:
      service:
        name: firewall
        description: Firewall service, based on nftables
        type: oneshot
        remain_after_exit: yes
        exec_start: /usr/local/bin/firewall-manager.sh start
        exec_stop: /usr/local/bin/firewall-manager.sh stop
        exec_reload: /usr/local/bin/firewall-manager.sh reload
        after:
        - network-online.target
        wanted_by:
        - multi-user.target
        on_changed: reloaded
        # state: started
        state: stopped
        enabled: yes
        replaces:
        - nftables-restore
