---
  - name: Install packages
    portage:
      package: "{{ item.name }}"
      state: "{{ item.state }}"
    with_items:
    - { name: net-firewall/iptables, state: absent }
    - { name: net-firewall/nftables, state: present }
    - { name: sys-apps/iproute2, state: present }
    tags:
    - packages

  - name: Sysctl setup
    sysctl:
      name: "{{ item.key }}"
      value: "{{ item.value }}"
      state: "{{ item.state|default('present') }}"
      sysctl_set: yes
      reload: yes
    with_items:
    - { key: net.ipv6.conf.all.disable_ipv6, value: 0 }
    - { key: net.ipv6.conf.default.disable_ipv6, value: 0 }
    - { key: net.ipv6.conf.lo.disable_ipv6, value: 0 }
    - { key: net.ipv6.conf.bridge_rt_0.disable_ipv6, value: 1 }
    - { key: net.ipv6.conf.all.forwarding, value: 1 }
    - { key: net.ipv6.conf.default.forwarding, value: 1 }
    - { key: net.ipv4.ip_forward, value: 1 }
    - { key: net.ipv4.conf.default.forwarding, value: 1 }
    when: inventory_hostname == 'gate'

  - name: Create conf directory
    file:
      path: "{{ config.location }}"
      state: directory
      owner: root
      group: root
      mode: 0644

  - name: Install manager script
    template:
      src: usr/local/bin/firewall-manager.sh.j2
      dest: /usr/local/bin/firewall-manager.sh
      owner: root
      group: root
      mode: 0744
    notify:
    - update firewall

  - name: Install firewall service
    template:
      src: etc/systemd/system/firewall.service.j2
      dest: /etc/systemd/system/firewall.service
      owner: root
      group: root
      mode: 0644
    notify:
    - systemd daemon reload
    - update firewall

  - name: make configuration
    template:
      src: etc/nftables/nftables.rules.j2
      dest: "{{ config.location }}/{{ config.filename }}"
      owner: root
      group: root
      mode: 0644
    notify:
    - update firewall

  - name: Stopping and disabling system firewall services
    service:
      name: nftables-restore
      enabled: no
      state: stopped

  - name: Enabling firewall service
    service:
      name: firewall
      enabled: yes
