---
  - name: Устанавливаем необходимые пакеты
    include_role:
      name: portage
      tasks_from: install_package
    vars:
      package: "{{ item }}"
    loop:
    - { name: net-misc/dhcp }
    - { name: net-misc/radvd }
    tags:
    - packages

  - name: Make dhcpd configuration
    template:
      src: "etc/dhcp/dhcpd{{ item }}.conf.j2"
      dest: "/etc/dhcp/dhcpd{{ item }}.conf"
      owner: root
      group: root
      mode: 0644
    loop:
      - 4
      - 6
    notify:
    - "restart dhcpd@{{ item }}"

  - name: Touch lease files
    copy:
      content: ""
      dest: "/var/lib/dhcp/dhcpd.leases.{{ item }}"
      force: no
      group: dhcp
      owner: dhcp
      mode: 0644
    loop:
      - 6
      - 4

  - name: Make radvd configuration
    template:
      src: etc/dhcp/radvd.conf.j2
      dest: /etc/dhcp/radvd.conf
      owner: radvd
      group: radvd
      mode: 0444
    notify:
    - restart radvd

  - name: Install dhcpd service
    template:
      src: etc/systemd/system/dhcpd@.service.j2
      dest: /etc/systemd/system/dhcpd@.service
      owner: root
      group: root
      mode: 0644
    notify:
    - systemd daemon reload
    - restart dhcpd

  - name: Install radvd service
    template:
      src: etc/systemd/system/radvd.service.j2
      dest: /etc/systemd/system/radvd.service
      owner: root
      group: root
      mode: 0644
    notify:
    - systemd daemon reload
    - restart radvd

  - name: Enabling dhcpd services
    service:
      name: "dhcpd@{{ item }}"
      enabled: yes
    loop:
      - 6
      - 4

  - name: Enabling radvd service
    service:
      name: radvd
      enabled: yes
