---
  - name: systemd daemon reload
    shell: systemctl daemon-reload

  - name: reload nginx
    service:
      name: nginx-daemon
      state: reloaded

  - name: restart nginx
    service:
      name: nginx-daemon
      state: restarted
