---
  - name: Устанавливаем необходимые пакеты
    include_role:
      name: portage
      tasks_from: install_package
    vars:
      package: "{{ item }}"
    loop:
    - { name: net-misc/openntpd, state: absent }
    - { name: net-misc/ntp, state: present }
    tags:
    - packages

  - name: Install ntpd configuration
    template:
      src: etc/ntpd/ntpd.conf.j2
      dest: /etc/ntp.conf
      owner: root
      group: root
      mode: 0644
    notify:
    - restart ntpd

  - name: Stopping and disabling system ntp-related service
    service:
      name: "{{ item }}"
      enabled: no
      state: stopped
    loop:
    - systemd-timesyncd

  - name: Enabling services
    service:
      name: ntpd
      enabled: yes
