---
  - name: Устанавливаем необходимые пакеты
    include_role:
      name: portage
      tasks_from: install_package
    vars:
      package: "{{ item }}"
    loop:
    - { name: net-misc/openntpd, state: absent }
    - { name: net-misc/ntp, state: present }
    tags:
    - packages

  - name: Install ntpd configuration
    template:
      src: etc/ntpd/ntpd.conf.j2
      dest: /etc/ntp.conf
      owner: root
      group: root
      mode: 0644
    notify:
    - restart ntpd

  - name: Настройка ротации лога ntpd
    import_role:
      name: logrotate
      tasks_from: rotate
    vars:
      lr:
        name: ntpd
        files:
        - /var/log/ntp.log
        options:
        - missingok
        - rotate 4
        - daily
        - compress

  - name: Stopping and disabling system ntp-related service
    systemd:
      name: systemd-timesyncd
      enabled: no
      state: stopped

  - name: Enabling services
    systemd:
      name: ntpd
      enabled: yes
    notify:
    - restart ntpd
