---
  # - name: Extract interface
  #   debug:
  #     msg: "{{target_interface}}"

  - name: "{{ target_interface.ifname }} : Setup interface"
    block:

    - name: "{{ target_interface.ifname }} : NetDev for interface"
      include_tasks: setup-netdev-for-interface.yaml
      when: target_interface.need_netdev is defined

    - name: "{{ target_interface.ifname }} : Static interface"
      include_tasks: setup-static-interface.yaml
      when: target_interface.type == 'static'

    - name: "{{ target_interface.ifname }} : DHCP interface"
      include_tasks: setup-dhcp-interface.yaml
      when: target_interface.type == 'dhcp'

    - name: "{{ target_interface.ifname }} : Bridge interface"
      include_tasks: setup-bridge-interface.yaml
      when: target_interface.type == 'bridge'

    - name: "{{ target_interface.ifname }} : Virtual interface"
      include_tasks: setup-virtual-interface.yaml
      when: target_interface.type == 'virtual'

    when: target_interface.ifname is defined
