---
  - name: "{{ target_interface.ifname }} : Setup systemd netdev files"
    template:
      src: "{{ item }}"
      dest: "/etc/systemd/network/{{ target_interface.ifname }}.netdev"
      owner: root
      group: root
      mode: 0644
    with_first_found:
    - "templates/{{ inventory_hostname }}/etc/systemd/network/{{ target_interface.ifname }}.netdev.j2"
    - etc/systemd/network/interface.netdev.j2
    notify:
    - restart networkd
