xorg_minimal_vt: 7

xorg_cursor_name: ComixCursors-Opaque-Red
# xorg_cursor_name: Bibata_Amber
xorg_cursor_size: 32

xorg_fonts_regular_name: Ubuntu
xorg_fonts_regular_size: 10

xorg_fonts_small_name: Ubuntu
xorg_fonts_small_size: 8

xorg_fonts_mono_name: Ubuntu Mono
xorg_fonts_mono_size: 10

xorg_theme_name: QtCurve

xorg_icons_name: Adwaita
