---
  - name: Подготавливаем переменные
    set_fact:
      ne_tf_name: "{{ script.name }}-to-node-exporter"

  - name: Устанавливаем скрипт-раннер
    template:
      owner: "{{ script.user }}"
      src: usr/local/bin/textfile-script-runner.j2.sh
      dest: "/usr/local/bin/{{ ne_tf_name }}-runner.sh"
      mode: 0755

  - name: Устанавливаем таймер для апдетящего скрипта
    import_role:
      name: systemd_unit
      tasks_from: setup_timer
    vars:
      timer:
        name: "{{ ne_tf_name }}"
        description: "{{ script.description }}"
        interval_sec: "{{ script.interval_sec }}"
        command: "/usr/local/bin/{{ ne_tf_name }}-runner.sh"
        user: "{{ script.user }}"
