---
  - name: Setup users
    user:
      name: "{{ item.name }}"
      password: "{{ item.password | password_hash('sha512', default_salt)}}"
      shell: /bin/zsh
      groups: "{{ item.groups|join(',') if item.name != 'root' else 'root' }}"
      expires: -1
      create_home: "{{ item.name != 'root' }}"
    loop: "{{ users }}"

  - name: Adding keys to users
    authorized_key:
      user: "{{ item.0.name }}"
      key: '{{ item.1 }}'
      state: present
    loop: "{{ users|product(ssh_keys)|list }}"
