---
  - name: Configuring systemd resolved
    template:
      src: etc/systemd/resolved.conf.j2
      dest: /etc/systemd/resolved.conf
      owner: root
      group: root
      mode: 0644
    notify:
    - restart resolved

  - name: Making simlink to resolved resolv.conf
    file:
      src: /run/systemd/resolve/resolv.conf
      dest: /etc/resolv.conf
      state: link
      owner: systemd-resolve
      group: systemd-resolve
      mode: 0644

  - name: Enabling systemd resolved service
    service:
      name: "{{ item }}"
      enabled: yes
    loop:
      - systemd-resolved
