---
  - name: Устанавливаем необходимые ебилды
    include_role:
      name: portage
      tasks_from: install_ebuild
    vars:
      ebuild:
        name: nftables_exporter
        category: app-metrics
        version: "9999"
        url: "https://raw.githubusercontent.com/Sheridan/nftables_exporter/master/gentoo/app-metrics/nftables_exporter/nftables_exporter-9999.ebuild"
        files:
        - url: "https://raw.githubusercontent.com/Sheridan/nftables_exporter/master/gentoo/app-metrics/nftables_exporter/files/nftables_exporter.yaml"
          name: nftables_exporter.yaml
    tags:
    - packages

  - name: Устанавливаем необходимые пакеты
    include_role:
      name: portage
      tasks_from: install_package
    vars:
      package: "{{ item }}"
    loop:
    - { name: app-metrics/nftables_exporter, unstable: yes }
    tags:
    - packages

  - name: Устанавливаем конфигурацию
    template:
      src: etc/nftables_exporter.yaml.j2
      dest: /etc/nftables_exporter.yaml
      owner: root
      group: root
      mode: 0644
    notify:
    - restart nftables_exporter

  - name: Установка сервиса nftables_exporter
    import_role:
      name: systemd_unit
      tasks_from: setup_service
    vars:
      service:
        name: nftables_exporter
        description: nftables exporter service
        restart: on-failure
        user: root
        exec_start: >
          /usr/bin/nftables_exporter
          --verbose
          --config=/etc/nftables_exporter.yaml
        after:
        - network-online.target
        wanted_by:
        - multi-user.target
        on_changed: restarted
        state: started
        enabled: yes

  - name: Connect exporter to prometheus
    import_role:
      name: prometheus
      tasks_from: connect_exporter
    vars:
      target:
        name: "{{ inventory_hostname }}_nftables_exporter"
        addr: "{{ '[::1]' if inventory_hostname == 'gate' else inventory_hostname }}"
        port: "{{ merged_vars.nftables_exporter.listen.port }}"
        job: nftables_exporter
