---
  - name: Устанавливаем необходимые пакеты
    include_role:
      name: portage
      tasks_from: install_package
    vars:
      package: "{{ item }}"
    loop:
    - { name: media-video/ffmpeg, unstable: no, use: { enabled: [X], disabled: [test] } }
    - { name: x11-misc/xdotool }
    tags:
    - packages

  - name: Устанавливаем скрипты
    template:
      src: "templates/usr/local/bin/{{ item }}"
      dest: "/usr/local/bin/{{ item }}"
      mode: 0755
    loop:
    - screen-capture.pl
    - registrator-road-compress.pl

  - name: Устанавливаем скрипт просмотра камеры
    template:
      src: "templates/usr/local/bin/ip-camera-view.sh.j2"
      dest: "/usr/local/bin/ip-camera-view-{{ i_camera }}.sh"
      mode: 0755
    loop: "{{ groups.cameras }}"
    loop_control:
      loop_var: i_camera
    when: "'stream_paths' in hostvars[i_camera].merged_vars"

  - name: Устанавливаем скрипты
    template:
      src: "templates/usr/local/bin/{{ item }}.j2"
      dest: "/usr/local/bin/{{ item }}"
      mode: 0755
    loop:
    - ip-camera-view-wall.sh
