---
  - name: Устанавливаем необходимые пакеты
    include_role:
      name: portage
      tasks_from: install_package
    vars:
      package: { name: app-metrics/prometheus }
    tags:
    - packages

  - name: create dirs for prometheus
    file:
      dest: "{{ item }}"
      state: directory
      owner: prometheus
    with_items:
      - /etc/prometheus/
      - /etc/prometheus/rules
      - /etc/prometheus/file_sd_configs
      - /var/lib/prometheus
      - /var/lib/prometheus/metrics

  - name: deploy prometheus configuration
    template:
      owner: root
      group: root
      src: "{{ item.file }}.j2"
      dest: "/{{ item.file }}"
      mode: "{{ item.mode }}"
    with_items:
        - { mode: "0644", file: 'etc/prometheus/prometheus.yaml' }
    notify:
    - restart prometheus

  - name: deploy nginx configuration
    import_role:
      name: nginx
      tasks_from: simple_proxy
    vars:
      target:
        name: prometheus
        addr: "{{ prometheus.listen.addr }}"
        port: "{{ prometheus.listen.port }}"

  - name: Connect prometheus exporter to prometheus
    import_role:
      name: prometheus
      tasks_from: connect_exporter
    vars:
      target:
        name: "{{ inventory_hostname }}_prometheus_exporter"
        addr: "[{{ prometheus.listen.addr }}]"
        port: "{{ prometheus.listen.port }}"
        job: prometheus_exporter

  - name: Install prometheus service
    import_role:
      name: systemd_unit
      tasks_from: setup_service
    vars:
      service:
        name: prometheus
        description: Prometheus Server
        restart: on-failure
        user: prometheus
        exec_start: >
          /usr/bin/prometheus
          --config.file=/etc/prometheus/prometheus.yaml
          --storage.tsdb.path=/var/lib/prometheus/metrics
          --storage.tsdb.retention="{{ prometheus.data_retention }}"
          --web.console.templates=/etc/prometheus/consoles
          --web.console.libraries=/etc/prometheus/console_libraries
          --web.listen-address=[{{ prometheus.listen.addr }}]:{{ prometheus.listen.port }}
          --web.enable-admin-api
        after:
        - network-online.target
        wanted_by:
        - multi-user.target
        on_changed: restarted
        state: started
        enabled: yes
