---
  - name: Устанавливаем необходимые пакеты
    include_role:
      name: portage
      tasks_from: install_package
    vars:
      package: "{{ item }}"
    loop:
    - { name: dev-python/requests }
    - { name: dev-python/python-systemd }
    - { name: dev-python/pyyaml }
    tags:
    - packages

  - name: Add loggerbot user
    user:
      name: "{{ loggerbot_user }}"
      comment: Logger Bot
      shell: /bin/false
      group: systemd-journal
      groups: portage
      create_home: no

  - name: create dirs for loggerbot
    file:
      dest: "{{ item }}"
      state: directory
      owner: "{{ loggerbot_user }}"
    with_items:
      - "{{ loggerbot_install_path }}"
      - "{{ loggerbot_config_path }}"

  - name: Copy loggerbot code
    copy:
      src: opt/loggerbot/loggerbot.py
      dest: "{{ loggerbot_install_path }}/loggerbot.py"
      owner: "{{ loggerbot_user }}"
      mode: 0644
    notify:
    - restart loggerbot

  - name: deploy loggerbot configuration
    template:
      src: etc/loggerbot/config.yaml.j2
      dest: /etc/loggerbot/config.yaml
      owner: "{{ loggerbot_user }}"
      mode: 0644
    notify:
    - restart loggerbot

  - name: Install loggerbot daemon service
    template:
      src: etc/systemd/system/loggerbot.service.j2
      dest: /etc/systemd/system/loggerbot.service
      owner: root
      group: root
      mode: 0644
    notify:
    - systemd daemon reload
    - restart loggerbot

  - name: Enabling services
    service:
      name: loggerbot
      enabled: yes
