---
  - name: Устанавливаем необходимые пакеты
    include_role:
      name: portage
      tasks_from: install_package
    vars:
      package: { name: net-dialup/rp-pppoe }
    tags:
    - packages

  - name: Установка паролей PPPoE
    template:
      src: etc/ppp/secrets.j2
      dest: "/etc/ppp/{{ item }}-secrets"
      owner: root
      group: root
      mode: 0644
    loop:
      - pap
      - chap
    notify:
    - restart pppoe

  - name: Установка настроек пиров PPPoE
    template:
      src: etc/ppp/peers/peer.j2
      dest: "/etc/ppp/peers/{{ provider }}"
      owner: root
      group: root
      mode: 0644
    loop: "{{ pppoe.providers }}"
    loop_control:
      loop_var: provider
    notify:
    - "restart pppoe@{{ provider }}"

  - name: Установка сервиса PPPoE
    template:
      src: etc/systemd/system/pppoe@.service.j2
      dest: /etc/systemd/system/pppoe@.service
      owner: root
      group: root
      mode: 0644
    notify:
    - systemd daemon reload
    - restart pppoe

  - name: Включение сервиса PPPoE
    systemd:
      name: "pppoe@{{ provider }}"
      enabled: yes
    loop: "{{ pppoe.providers }}"
    loop_control:
      loop_var: provider
