---
  - name: Устанавливаем необходимые пакеты
    include_role:
      name: portage
      tasks_from: install_package
    vars:
      package: { name: net-dialup/rp-pppoe }
    tags:
    - packages

  - name: Setup PPPoE passwords
    template:
      src: etc/ppp/secrets.j2
      dest: "/etc/ppp/{{ item }}-secrets"
      owner: root
      group: root
      mode: 0644
    loop:
      - pap
      - chap
    notify:
    - restart pppoe

  - name: Setup PPPoE peer options
    template:
      src: etc/ppp/peers/peer.j2
      dest: "/etc/ppp/peers/{{ item }}"
      owner: root
      group: root
      mode: 0644
    loop: "{{ pppoe.providers }}"
    notify:
    - "restart pppoe@{{ item }}"

  - name: Setup PPPoE service
    template:
      src: etc/systemd/system/pppoe@.service.j2
      dest: /etc/systemd/system/pppoe@.service
      owner: root
      group: root
      mode: 0644
    notify:
    - systemd daemon reload
    - restart pppoe
    # TODO: Добавить поднятие бриджа

  - name: Enabling PPPoE services
    service:
      name: "pppoe@{{ item }}"
      enabled: yes
    loop: "{{ pppoe.providers }}"
