---
  - name: Устанавливаем необходимые пакеты
    include_role:
      name: portage
      tasks_from: install_package
    vars:
      package: { name: sys-apps/smartmontools, use: { enabled: [update_drivedb], disabled: [daemon] } }
    tags:
    - packages

  - name: Обновляем БД
    shell: update-smart-drivedb
    tags:
    - packages

  - name: Устанавливаем скрипт - сборщик метрик
    copy:
      src: usr/local/bin/smartctl-exporter.sh
      dest: /usr/local/bin/smartctl-exporter.sh
      owner: root
      group: root
      mode: 0755

  - name: Подключаем к нода экспортеру
    import_role:
      name: node_exporter
      tasks_from: setup_textfile_script
    vars:
      script:
        name: "smartctl"
        description: "S.M.A.R.T. metrics collector"
        interval_sec: "{{ 60 * 3 }}"
        command: /usr/local/bin/smartctl-exporter.sh
        user: root
