---
  - name: Добавляем ключ репозитория
    apt_key:
      url: https://repos.influxdata.com/influxdb.key
      state: present
    register: r_telegraf_key_added

  - name: Добавляем репозиторий
    apt_repository:
      repo: deb https://repos.influxdata.com/ubuntu {{ ansible_lsb.codename }} stable
      state: present
    register: r_telegraf_repo_added

  - name: Устанавливаем необходимые пакеты
    apt:
      name:
      - telegraf
      state: present
      update_cache: "{{ r_telegraf_key_added.changed or r_telegraf_repo_added.changed }}"
