---
  network:
  - name: "Internal"
    mac: "00:12:41:ac:3c:ee"
    ip: "{{ query('ship', 'ip', 170) }}"
    network: 'home'
    type: 'dhcp'

  firewall:
    host_to_internet:
      services:
      - dvr_kitchen
