---
  network:
  - name: "Internal ethernet"
    ifname: "ethernet_0"
    mac: "00:22:15:96:f2:6b"
    # duid: "00:01:00:01:1d:23:e1:f7:00:22:15:96:f3:85"
    ip: "{{ query('ship', 'ip', 22) }}"
    network: 'home'
    type: 'dhcp'

  - name: "Internal wifi"
    ifname: "wifi_0"
    mac: "00:15:af:ef:5b:b4"
    # duid: "00:02:00:00:ab:11:47:f9:ac:16:b7:b3:a2:d7"
    ip: "{{ query('ship', 'ip', 23) }}"
    network: 'home'
    type: 'dhcp'

  firewall:
    host_to_internet:
      services:
      - sber_online
