---
  network:
  - name: "Internal"
    ifname: "internal_0"
    dns:
      aliases:
        - grafana
        - prometheus
        - ntp
    mac: "94:de:80:6c:66:b0"
    ip: "{{ query('ship', 'ip', 1) }}"
    network: 'home'
    type: 'static'

  - name: "External KIS"
    ifname: "external_kis_0"
    tunnel: "external_he_0"
    dns:
      aliases:
        - www
    mac: "50:3e:aa:04:8f:b0"
    ip:
      ipv4: "{{ query('ship', 'kis_ip', 2) }}"
    network: 'kis'
    type: 'static'

  - name: "External RT"
    ifname: "external_rt_0"
    type: "pppoe"
    bridge: "bridge_rt_0"
    ip:
      ipv4: 'dynamic'

  - name: "Bridge RT"
    ifname: "bridge_rt_0"
    mac: "50:3e:aa:04:cb:21"
    type: "bridge"
    ip:
      ipv4: 'dynamic'

  - name: "External HeNet"
    dns:
      aliases:
        - www
    ifname: "external_he_0"
    need_netdev: yes
    ip:
      ipv6: "{{ query('ship', 'henet_ip', 2) }}"
    network: 'henet'
    type: 'static'

  firewall:
    to_host:
      proxy:
        name: "Proxy"
        ports:
        - 3128-3129
        interfaces:
          - "internal"
      dhcpd:
        name: "DHCPd"
        ports:
        - 67
        - 68
        - 546
        - 547
        interfaces:
          - "internal"
      dns:
        name: "Domain"
        ports:
        - 53
        interfaces:
          - "internal"
          - "external_kis"
          - "external_he"
      ssh:
        name: "SSH"
        ports:
        - 22
        interfaces:
          - "internal"
          - "external_kis"
          - "external_he"
      web:
        name: "web"
        ports:
        - 80
        - 443
        interfaces:
          - "internal"
      ntpd:
        name: "ntpd"
        ports:
        - 123
        interfaces:
          - "internal"

  node_exporter:
    collectors:
      enabled:
      - textfile
      - ntp

  kernel:
    genkernel:
      enabled: yes
      options:
        - btrfs
        - no-zfs
        - no-lvm
        - no-mdadm
        - no-dmraid
        - no-luks

  users:
  - name: root
    password: yv9wtb9odz3ogh6qzy4g5cysww3guexq
  - name: sheridan
    password: g7xjy83yuh4boy6asbbt996hpfmomrz4
    groups:
    - users
    - tty
    - disk
    - wheel
    - uucp
    - console
    - audio
    - cdrom
    - video
    - cdrw
    - usb
    - utmp

  zsh:
    theme: "gentoo"
    plugins:
    - git
