---
  network:
  - name: "Internal"
    mac: "e0:62:90:0f:24:55"
    ip: "{{ query('ship', 'ip', 167) | first }}"
    network: 'home'
    type: 'dhcp'

  stream_paths:
    high:
      port: 8554
      path: live0.265
    low:
      port: 8554
      path: live1.265

  dvr:
    host: dvr-kitchen
    channel: 1
