---
  network:
  - name: "Internal"
    mac: "e0:62:90:08:55:a7"
    ip: "{{ query('ship', 'ip', 168) }}"
    network: 'home'
    type: 'dhcp'

  stream_paths:
    high:
      port: 554
      path: live0.265
    low:
      port: 554
      path: live1.265

  dvr:
    host: dvr-kitchen
    channel: 1
