---
  network:
  - name: "Internal"
    mac: "00:12:41:ca:ce:00"
    ip: "{{ query('ship', 'ip', 172) | first }}"
    network: 'home'
    type: 'dhcp'

  stream_paths:
    high:
      port: 554
      path: live0.265
    low:
      port: 554
      path: live1.265

  dvr:
    host: dvr-kitchen
    channel: 3
