---
  network:
  - name: "Internal"
    mac: "ec:71:db:e9:ce:86"
    ip: "{{ query('ship', 'ip', 166) }}"
    network: 'home'
    type: 'dhcp'

  stream_paths:
    high:
      port: 554
      path: h264Preview_01_main
    low:
      port: 554
      path: h264Preview_01_sub

  dvr:
    host: dvr-kitchen
    channel: 3
