---
  network:
  - name: "Internal"
    mac: "50:46:5d:7b:50:6f"
    duid: "00:04:0a:f4:c4:36:e8:59:5a:99:4a:14:b7:6a:8d:9a:9f:0c"
    ip: "{{ query('ship', 'ip', 100) }}"
    network: 'home'
    type: 'dhcp'
