---
  network:
  - name: "Internal"
    mac: "38:fb:14:a9:ea:56"
    ip: "{{ query('ship', 'ip', 11) }}"
    network: 'home'
    type: 'dhcp'

  firewall:
    host_to_internet:
      navitel:
        name: "Navitel"
        ports:
        - 7443
        - 7450
        - 7390
        - 6447
        - 7275
        - 5684
