---
  network:
  - name: "Internal"
    ifname: "internal_0"
    mac: "94:de:80:7c:8b:ee"
    duid: "00:02:00:00:ab:11:7a:1c:61:eb:ac:c3:f0:f3"
    ip: "{{ query('ship', 'ip', 10) }}"
    network: 'home'
    type: 'dhcp'

  kernel:
    genkernel:
      enabled: no

  users:
  - name: root
    password: gfhjkm
  - name: sheridan
    password: gfhjkm
    groups:
    - users
    - tty
    - disk
    - wheel
    - uucp
    - console
    - audio
    - cdrom
    - video
    - games
    - cdrw
    - usb
    - kdm
    - utmp
    - android
    - wireshark
    - vboxusers
    - docker

  zsh:
    theme: "gentoo"
    plugins:
    - git
    - ssh-agent
