---
  network:
  - name: "Internal"
    ifname: "internal_0"
    mac: "94:de:80:7c:8b:ee"
    duid: "00:02:00:00:ab:11:7a:1c:61:eb:ac:c3:f0:f3"
    ip: "{{ query('ship', 'ip', 10) }}"
    network: 'home'
    type: 'dhcp'

  firewall:
    to_host:
      ssh:
        name: "SSH"
        ports:
        - 22
        interfaces:
        - "internal"
      web:
        name: "web"
        ports:
        - 80
        - 443
        interfaces:
        - "internal"
      dhcpc:
        name: "DHCPc"
        ports:
        - 68
        - 546
        interfaces:
        - "internal"

  kernel:
    genkernel:
      enabled: no

  users:
  - name: root
    password: gfhjkm
  - name: sheridan
    password: gfhjkm
    groups:
    - users
    - tty
    - disk
    - wheel
    - uucp
    - console
    - audio
    - cdrom
    - video
    - games
    - cdrw
    - usb
    - kdm
    - utmp
    - android
    - wireshark
    - vboxusers
    - docker

  zsh:
    theme: "gentoo"
    plugins:
    - git
    - ssh-agent

  # observer:
  #   entryes:
  #   - type: journal
  #     regexp: '(device detected|Attached)'
  #     title: Devices

  Xorg:
    videocards:
      first:
        name: "NVIDIA Corporation GP107 [GeForce GTX 1050]"
        pci: "01:00.0"
      second:
        name: "NVIDIA Corporation GF108 [GeForce GT 630]"
        pci: "08:00.0"
    monitors:
      center:
        name: "LG 22MP55"
        video_out: "HDMI-0"
        position:
          base: yes
        mode:
          width: 1920
          height: 1080
          rate: 60
      left:
        name: "LG L1740BQ"
        video_out: "VGA-1-1"
        position:
          where: left-of
          from: center
        mode:
          width: 1280
          height: 1024
          rate: 60
      right:
        name: "LG L1740PQ"
        video_out: "DP-1"
        position:
          where: right-of
          from: center
        mode:
          width: 1280
          height: 1024
          rate: 60
      top:
        name: "ViewSonic WX2235WM-EU"
        video_out: "DVI-I-1-1"
        position:
          where: above
          from: center
        mode:
          width: 1680
          height: 1050
          rate: 60
