---
  wiki:
    user:
      name: wiki
      pw: "{{ wiki_secrets.system_user_pw }}"
    path:
      work: /opt/wiki/packages/mediawiki
      prod: /opt/wiki/production/mediawiki
      skins: /opt/wiki/production/mediawiki/skins
      extensions: /opt/wiki/production/mediawiki/extensions
      upload: /opt/wiki/production/mediawiki/upload
    wiki_version:
      major: 1
      minor: 32
    extensions:
      - { repo: "https://github.com/wikimedia/mediawiki-extensions-YouTube", name: YouTube }
      - { repo: "https://github.com/wikimedia/mediawiki-extensions-Widgets", name: Widgets }
      - { repo: "https://github.com/wikimedia/mediawiki-extensions-GraphViz", name: GraphViz, ver: master }
      - { repo: "https://github.com/wikimedia/mediawiki-extensions-CodeMirror", name: CodeMirror }
    skins:
      - { repo: "https://github.com/dolfinus/DarkVector.git", name: DarkVector, ver: HEAD }
