---
  # rx: \(\?P<(.+?)>.+?\)
  # rp: ${$1}
  - name: Устанавливаем необходимые пакеты
    include_role:
      name: portage
      tasks_from: install_package
    vars:
      package: "{{ item }}"
    loop:
    - { name: dev-python/requests }
    - { name: dev-python/python-systemd }
    - { name: dev-python/pyyaml }
    - { name: dev-python/bottle }
    tags:
    - packages

  # - name: Add observer user
  #   user:
  #     name: "{{ observer_user }}"
  #     comment: Observer and alerter
  #     shell: /bin/false
  #     group: root
  #     groups:
  #     - portage
  #     - systemd-journal
  #     create_home: no

  - name: Setup observer user
    import_role:
      name: system_user
      tasks_from: setup_user
    vars:
      user:
        name: "{{ observer_user }}"
        comment: Observer and alerter
        groups:
        - root
        - portage
        - systemd-journal

  - name: Создаём каталоги для наблюдателя
    file:
      dest: "{{ item }}"
      state: directory
      owner: "{{ observer_user }}"
      group: "{{ observer_user }}"
      mode: 0755
    with_items:
      - "{{ observer_install_path }}"
      - "{{ observer_config_path }}"
      - "{{ observer_templates_path }}"
      - "{{ storage_folder }}"

  - name: Клонируем observer
    git:
      repo: https://github.com/Sheridan/observer.git
      dest: '{{ observer_install_path }}'
    notify:
    - restart observer

  - name: deploy observer configuration
    template:
      src: etc/observer/config.yaml.j2
      dest: /etc/observer/config.yaml
      owner: '{{ observer_user }}'
      mode: 0644
    notify:
    - restart observer

  - name: Проверка наличия директорий шаблонов
    file:
      path: '{{ observer_templates_path }}/{{ item.path }}'
      state: directory
      mode: 0755
      owner: '{{ observer_user }}'
    with_filetree: templates/etc/observer/templates/
    when: item.state == 'directory'

  - name: Копируем шаблоны
    template:
      src: '{{ item.src }}'
      dest: '{{ observer_templates_path }}/{{ item.path }}'
      mode: 0644
      owner: '{{ observer_user }}'
    with_filetree: templates/etc/observer/templates/
    when: item.state == 'file'


  - name: Install observer service
    import_role:
      name: systemd_unit
      tasks_from: setup_service
    vars:
      service:
        name: observer
        description: Observer service for pushing alerts from many to many
        user: "{{ observer_user }}"
        restart_sec: 30s
        exec_start: >-
          /usr/bin/python3
          -u
          {{ observer_install_path }}/observer.py
          {{ observer_config_path }}/config.yaml
        after:
        - network-online.target
        wanted_by:
        - multi-user.target
        on_changed: restarted
        state: started
        enabled: yes
