---
  - name: Устанавливаем необходимые пакеты
    include_role:
      name: portage
      tasks_from: install_package
    vars:
      package: { name: net-analyzer/telegraf, unstable: yes, x86_as_amd64: yes }
