---
  - name: restart prometheus
    systemd:
      name: prometheus
      state: restarted

  - name: restart gate prometheus
    systemd:
      name: prometheus
      state: restarted
    delegate_to: gate
