---
  - name: Устанавливаем необходимые пакеты
    include_role:
      name: portage
      tasks_from: install_package
    vars:
      package: "{{ item }}"
    loop:
    - { name: x11-wm/awesome, unstable: yes, use: { enabled: [dbus], disabled: [gnome, test, luajit] } }
    - { name: sci-calculators/speedcrunch }
    - { name: app-admin/keepassxc, use: { enabled: [autotype, browser, network, yubikey], disabled: [debug, test] } }
    - { name: x11-misc/qtfm }
    - { name: media-gfx/flameshot, unstable: yes }
    - { name: x11-terms/kitty, unstable: yes, use: { enabled: [imagemagick], disabled: [debug, doc] } }
    - { name: x11-terms/qterminal }
    tags:
    - packages

  - name: Создаём временные каталоги
    file:
      dest: "{{ tmp_workdir }}/{{item}}"
      state: directory
    loop:
    - awesome
    - awesome/fatcow
    delegate_to: localhost

  - name: Скачиваем иконки
    get_url:
      url: https://www.fatcow.com/images/fatcow-icons/fatcow-hosting-icons-3.9.2-all.zip
      dest: "{{ tmp_workdir }}/awesome/fatcow.zip"
    delegate_to: localhost
    ignore_errors: "{{ ansible_check_mode }}"
    tags:
    - awesome_icons

  - name: Распаковываем иконки
    unarchive:
      src: "{{ item }}"
      dest: "{{ tmp_workdir }}/awesome/fatcow"
    loop:
    - "{{ tmp_workdir }}/awesome/fatcow.zip"
    - "{{ tmp_workdir }}/awesome/fatcow/fatcow-hosting-icons-3.9.2.zip"
    delegate_to: localhost
    ignore_errors: "{{ ansible_check_mode }}"
    tags:
    - awesome_icons

  - name: Деплоим в юзера
    include_tasks: user_part.yaml
    loop: "{{ users }}"
    loop_control:
      loop_var: user
    when: user.name != 'root'
