---
  - name: Устанавливаем необходимые пакеты
    include_role:
      name: portage
      tasks_from: install_package
    vars:
      package: "{{ item }}"
    loop:
    - { name: x11-wm/awesome, unstable: yes, use: { enabled: [dbus, luajit], disabled: [gnome, test] } }
    - { name: x11-misc/lightdm, use: { enabled: [gtk, introspection, qt5, vala], disabled: [gnome, audit] }}
    - { name: media-fonts/emojione-color-font }
    - { name: media-fonts/twemoji-color-font }
    - { name: sci-calculators/speedcrunch }
    - { name: app-admin/keepassxc, use: { enabled: [autotype, browser, network, yubikey], disabled: [debug, test] } }
    - { name: x11-misc/qtfm }
    - { name: media-gfx/flameshot, unstable: yes }
    - { name: x11-terms/kitty, unstable: yes, use: { enabled: [imagemagick], disabled: [debug, doc] } }
    - { name: x11-terms/qterminal }
    # - { name: x11-themes/adwaita-icon-theme }
    # - { name: x11-themes/adwaita-qt }
    # - { name: x11-themes/gtk-engines-adwaita }
    - { name: x11-themes/qtcurve, use: { enabled: [gtk, nls, qt5] } }
    - { name: x11-themes/comix-xcursors, use: { enabled: [opaque], disabled: [lefthanded] } }
    - { name: media-fonts/ubuntu-font-family }
    - { name: x11-misc/qt5ct, unstable: no, x86_as_amd64: yes }
    - { name: x11-themes/gtk-chtheme }
    tags:
    - packages

  - name: Создаём временные каталоги
    file:
      dest: "{{ tmp_workdir }}/{{item}}"
      state: directory
    loop:
    - awesome
    - awesome/fatcow
    delegate_to: localhost

  - name: Скачиваем иконки
    get_url:
      url: https://www.fatcow.com/images/fatcow-icons/fatcow-hosting-icons-3.9.2-all.zip
      dest: "{{ tmp_workdir }}/awesome/fatcow.zip"
    delegate_to: localhost

  - name: Распаковываем иконки
    unarchive:
      src: "{{ item }}"
      dest: "{{ tmp_workdir }}/awesome/fatcow"
    loop:
    - "{{ tmp_workdir }}/awesome/fatcow.zip"
    - "{{ tmp_workdir }}/awesome/fatcow/fatcow-hosting-icons-3.9.2.zip"
    delegate_to: localhost

  - name: Устанавливаем xrandr скрипт
    template:
      src: usr/local/bin/xrandrapply.j2.sh
      dest: /usr/local/bin/xrandrapply.sh
      mode: 0755
    when: merged_vars.Xorg.monitors | length > 1

  - name: Деплоим в юзера
    include_tasks: user_part.yaml
    loop: "{{ users }}"
    loop_control:
      loop_var: user
    when: user.name != 'root'
