---
  - name: Устанавливаем необходимые пакеты
    apt:
      name:
      - homed-zigbee
      state: latest
    notify:
    - restart homed-zigbee
    tags:
    - packages

  - name: create dirs for homed-zigbee
    file:
      dest: "{{ item }}"
      state: directory
      owner: "{{ homed_user }}"
      recurse: yes
    loop:
      - "{{ homed_conf_root }}"
      - "{{ homed_zigbee_data_root }}"
      - "{{ homed_zigbee_data_root }}/external"
      - "{{ homed_zigbee_data_root }}/ota"
      - "{{ homed_zigbee_src }}"

  - name: Git homed-zigbee checkout
    git:
      repo: 'https://github.com/u236/homed-service-zigbee.git'
      dest: "{{ homed_zigbee_src }}"
      force: yes
    become: yes
    become_user: "{{ homed_user }}"
    tags:
    - packages
    register: r_hz_git

  - name: Копируем описание девайсов...
    synchronize:
      src: "{{ homed_zigbee_src }}/deploy/data/usr/share/homed-zigbee/"
      dest: "{{ homed_zigbee_data_root }}/external"
      recursive: yes
      delete: yes
      rsync_opts: "--exclude=A_sheridan.json"
    delegate_to: "{{ inventory_hostname }}"
    tags:
    - packages
    when: r_hz_git.changed

  - name: Install HOMEd zigbee service
    import_role:
      name: systemd_unit
      tasks_from: setup_service
    vars:
      service:
        name: "homed-zigbee-daemon@"
        description: "The IoT HOMEd Zigbee daemon, instance %i"
        exec_start_pre: "/bin/rm -f {{ homed_zigbee_data_root }}/%i/properties.json"
        exec_start: "/usr/bin/homed-zigbee -c {{ homed_conf_root }}/zigbee_%i.conf -l /tmp/homed_%i.lock"
        syslog_identifier: "homed-zigbee-%i"
        user: "{{ homed_user }}"
        group: dialout
        kill_signal: SIGTERM
        restart: on-failure
        environments:
        - { name: LD_LIBRARY_PATH, value: "/usr/lib" }
        after:
        - network-online.target
        wanted_by:
        - multi-user.target
        on_changed: restarted
        enabled: yes
        replaces:
        - homed-zigbee
        - homed-zigbee-daemon

  - name: Инстансы
    include_tasks: zigbee_instance.yaml
    loop: "{{ homed_zigbee_instances }}"
    loop_control:
      loop_var: i_zigbee_instance
