---
  - name: Устанавливаем телеграфу конфиг для S.M.A.R.T.
    template:
      owner: telegraf
      src: etc/telegraf/telegraf.d/smart.conf.j2
      dest: /etc/telegraf/telegraf.d/smart.conf
      mode: 0644
    notify:
    - restart telegraf

  - name: Привелигелируем пользователя telegraf
    include_role:
      name: sudoers
      tasks_from: add_sudoer
    vars:
      user: telegraf
    notify:
    - restart telegraf
