---
  - name: Устанавливаем необходимые пакеты
    include_tasks: "{{ ansible_distribution }}/packages.yaml"
    tags:
    - packages
    # notify:
    # - restart telegraf

  - name: Устанавливаем основной конфиг
    template:
      owner: telegraf
      src: etc/telegraf/telegraf.conf.j2
      dest: /etc/telegraf/telegraf.conf
      mode: 0644
    notify:
    - restart telegraf

  - block:
    - name: Устанавливаем ping экспортер
      include_tasks: deploy_ping_plugin.yaml
    # block
    when: inventory_hostname == 'gate'

  - name: Подключаем к прометею
    import_role:
      name: prometheus
      tasks_from: connect_exporter
    vars:
      target:
        name: "{{ inventory_hostname }}_telegraf"
        addr: "{{ '[::1]' if inventory_hostname == 'gate' else inventory_hostname }}"
        port: "{{ merged_vars.telegraf.listen.port }}"
        job: telegraf

  - name: Install telegraf service
    import_role:
      name: systemd_unit
      tasks_from: setup_service
    vars:
      service:
        name: telegraf-daemon
        description: Telegraf server daemon
        restart_sec: 2s
        exec_start: /usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d
        exec_reload: /bin/kill -HUP $MAINPID
        #capability_bounding_set: CAP_NET_RAW CAP_NET_ADMIN
        #ambient_capabilities: CAP_NET_RAW CAP_NET_ADMIN
        user: telegraf
        after:
        - network-online.target
        wanted_by:
        - multi-user.target
        on_changed: restarted
        state: started
        enabled: yes
        replaces:
        - telegraf

#  - name: Enabling services
#    systemd:
#      name: telegraf
#      enabled: yes
#    notify:
#    - restart telegraf
