---
  - name: Устанавливаем необходимые пакеты
    include_role:
      name: portage
      tasks_from: install_package
    vars:
      package: { name: net-misc/openssh }
    tags:
    - packages

  - name: Configuring ssh server
    template:
      src: etc/ssh/sshd_config.j2
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: 0600
    notify:
    - restart sshd

  - name: Install sshd service
    import_role:
      name: systemd_unit
      tasks_from: setup_service
    vars:
      service:
        name: ssh-daemon
        description: OpenSSH server daemon
        restart_sec: 16s
        exec_start_pre: /usr/bin/ssh-keygen -A
        exec_start: /usr/sbin/sshd -D -e
        exec_reload: /bin/kill -HUP $MAINPID
        after:
        - network-online.target
        wanted_by:
        - multi-user.target
        on_changed: restarted
        state: started
        enabled: yes
        replaces:
        - sshd
