---
  - name: Устанавливаем необходимые пакеты
    include_role:
      name: portage
      tasks_from: install_package
    vars:
      package: { name: net-misc/openssh }
    tags:
    - packages

  - name: Configuring ssh server
    template:
      src: etc/ssh/sshd_config.j2
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: 0600
    notify:
    - restart sshd

  - name: Install ssh daemon service
    template:
      src: etc/systemd/system/ssh-daemon.service.j2
      dest: /etc/systemd/system/ssh-daemon.service
      owner: root
      group: root
      mode: 0644
    notify:
    - systemd daemon reload
    - restart sshd

  - name: Stopping and disabling system sshd
    service:
      name: sshd
      enabled: no
      state: stopped

  - name: Enabling services
    service:
      name: ssh-daemon
      enabled: yes
